package crud;

import Metodos.MetodosBD2;
import Metodos.Placeholder;
import Metodos.SetColores;
import Metodos.SetColores2;
import Metodos.SetColores3;


public class CrearCliente extends javax.swing.JPanel {

    MetodosBD2 metodos = new MetodosBD2();
    
    public CrearCliente() {
        initComponents();
        
        SetColores3 color1 = new SetColores3(panel1);
        SetColores color2 = new SetColores(guardarBtn);
        
        Placeholder caja1 = new Placeholder("Ingrese el ID", idTxt);
        Placeholder caja2 = new Placeholder("Ingrese el nombre",nombreTxt);
        Placeholder caja3 = new Placeholder("Ingrese el apellido",apellidoTxt);
        Placeholder caja4 = new Placeholder("Ingrese el NIT/CF",nitTxt);
        Placeholder caja5 = new Placeholder("Ingrese la dirección",direccionTxt);
        Placeholder caja6 = new Placeholder("Ingrese el usuario",usuarioTxt);
        
        SetColores3 ctxt1 = new SetColores3(idTxt);
        SetColores3 ctxt2 = new SetColores3(nombreTxt);
        SetColores3 ctxt3 = new SetColores3(apellidoTxt);
        SetColores3 ctxt4 = new SetColores3(nitTxt);
        SetColores3 ctxt5 = new SetColores3(direccionTxt);
        SetColores3 ctxt6 = new SetColores3(usuarioTxt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        idTxt = new javax.swing.JTextField();
        nombreTxt = new javax.swing.JTextField();
        apellidoTxt = new javax.swing.JTextField();
        nitTxt = new javax.swing.JTextField();
        direccionTxt = new javax.swing.JTextField();
        usuarioTxt = new javax.swing.JTextField();
        generoTxt = new javax.swing.JComboBox<>();
        guardarBtn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idTxt.setBorder(null);
        panel1.add(idTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 210, 30));

        nombreTxt.setBorder(null);
        panel1.add(nombreTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 210, 30));

        apellidoTxt.setBorder(null);
        panel1.add(apellidoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 210, 30));

        nitTxt.setBorder(null);
        panel1.add(nitTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 210, 30));

        direccionTxt.setBorder(null);
        panel1.add(direccionTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, 240, 30));

        usuarioTxt.setBorder(null);
        panel1.add(usuarioTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 170, 30));

        generoTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        panel1.add(generoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(572, 230, 170, -1));

        guardarBtn.setBackground(new java.awt.Color(102, 102, 102));
        guardarBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        guardarBtn.setForeground(new java.awt.Color(255, 255, 255));
        guardarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guardarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                guardarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                guardarBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                guardarBtnMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel1.setText("Guardar");

        javax.swing.GroupLayout guardarBtnLayout = new javax.swing.GroupLayout(guardarBtn);
        guardarBtn.setLayout(guardarBtnLayout);
        guardarBtnLayout.setHorizontalGroup(
            guardarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guardarBtnLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel1)
                .addContainerGap(107, Short.MAX_VALUE))
        );
        guardarBtnLayout.setVerticalGroup(
            guardarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guardarBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel1.add(guardarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 270, 40));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 40, 400));
        panel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 170, 10));
        panel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 210, 10));
        panel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 210, 10));
        panel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 210, 10));
        panel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 210, 10));
        panel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 240, 10));

        jLabel2.setText("Id Cliente");
        panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        jLabel3.setText("Nombre");
        panel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        jLabel4.setText("Apellido");
        panel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        jLabel5.setText("Nit /CF");
        panel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        jLabel6.setText("Direeción");
        panel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, -1, -1));

        jLabel7.setText("Usuario");
        panel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, -1, -1));

        jLabel8.setText("Género");
        panel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 50, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void guardarBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarBtnMousePressed
        // TODO add your handling code here:
        metodos.nuevoCliente(idTxt.getText(), nombreTxt.getText(), apellidoTxt.getText(), nitTxt.getText(), 
                direccionTxt.getText(), usuarioTxt.getText(), generoTxt.getSelectedItem().toString());
        
        idTxt.setText("");
        nombreTxt.setText("");
        apellidoTxt.setText("");
        nitTxt.setText("");
        direccionTxt.setText("");
        usuarioTxt.setText("");
        
    }//GEN-LAST:event_guardarBtnMousePressed

    private void guardarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarBtnMouseEntered
        // TODO add your handling code here:
        SetColores2 color = new SetColores2(guardarBtn);
    }//GEN-LAST:event_guardarBtnMouseEntered

    private void guardarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarBtnMouseExited
        // TODO add your handling code here:
        SetColores color = new SetColores(guardarBtn);
    }//GEN-LAST:event_guardarBtnMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidoTxt;
    private javax.swing.JTextField direccionTxt;
    private javax.swing.JComboBox<String> generoTxt;
    private javax.swing.JPanel guardarBtn;
    private javax.swing.JTextField idTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField nitTxt;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JPanel panel1;
    public javax.swing.JTextField usuarioTxt;
    // End of variables declaration//GEN-END:variables
}
