package crud;

import Metodos.Conexion;
import Metodos.MetodosBD2;
import Metodos.PersonalizarTabla;
import Metodos.PersonalizarTabla2;
import Metodos.Placeholder;
import Metodos.SetColores;
import Metodos.SetColores2;
import Metodos.SetColores3;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;


public class CrudEmpleado extends javax.swing.JPanel {

    MetodosBD2 metodos = new MetodosBD2();
    String [] botones = {"Aceptar", "Cancelar"}; //Para botones de opciones de los JOption Pane.showOptionDialog
    public CrudEmpleado() {
        initComponents();
        
        mostrarEmpleados();
        SetColores3 color1 = new SetColores3(panel1);
        SetColores color2 = new SetColores(crearBtn);
        
        SetColores3 ctxt1 = new SetColores3(idTtx);
        SetColores3 ctxt2 = new SetColores3(nombreTxt);
        
        Placeholder caja1 = new Placeholder("Buscar por ID", idTtx);
        Placeholder caja2 = new Placeholder("Buscar por nombre", nombreTxt);
        
        PersonalizarTabla2 personalizar = new PersonalizarTabla2(tablaEmpleado);
        
        metodos.verItem(Modificar, Eliminar);//
        metodos.verBoton(crearBtn);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        Modificar = new javax.swing.JMenuItem();
        Eliminar = new javax.swing.JMenuItem();
        panel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEmpleado = new javax.swing.JTable();
        idTtx = new javax.swing.JTextField();
        nombreTxt = new javax.swing.JTextField();
        crearBtn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(Modificar);

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(Eliminar);

        setPreferredSize(new java.awt.Dimension(880, 420));

        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaEmpleado.setComponentPopupMenu(jPopupMenu1);
        tablaEmpleado.setShowGrid(true);
        jScrollPane1.setViewportView(tablaEmpleado);

        panel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 870, 280));

        idTtx.setBorder(null);
        idTtx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTtxActionPerformed(evt);
            }
        });
        panel1.add(idTtx, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 180, 30));

        nombreTxt.setBorder(null);
        nombreTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTxtActionPerformed(evt);
            }
        });
        panel1.add(nombreTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 180, 30));

        crearBtn.setBackground(new java.awt.Color(153, 153, 153));
        crearBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        crearBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        crearBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                crearBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                crearBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                crearBtnMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Crear nuevo empleado");

        javax.swing.GroupLayout crearBtnLayout = new javax.swing.GroupLayout(crearBtn);
        crearBtn.setLayout(crearBtnLayout);
        crearBtnLayout.setHorizontalGroup(
            crearBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearBtnLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        crearBtnLayout.setVerticalGroup(
            crearBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel1.add(crearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 190, 30));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 20, 120));
        panel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 180, 10));
        panel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 180, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void idTtxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTtxActionPerformed
        // TODO add your handling code here:
        mostrarEmpleados();
    }//GEN-LAST:event_idTtxActionPerformed

    private void nombreTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTxtActionPerformed
        // TODO add your handling code here:
        mostrarEmpleados();
    }//GEN-LAST:event_nombreTxtActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // TODO add your handling code here:
        int x=JOptionPane.showOptionDialog(this, "¿Desea eliminar el registro?", "Eliminar", 
                JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, botones, botones[0]);
        if(x==0){
            eliminar();
            mostrarEmpleados();
        }else{
           JOptionPane.showMessageDialog(this, "Proceso cancelado");
        }
    }//GEN-LAST:event_EliminarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        // TODO add your handling code here:
        int x=JOptionPane.showOptionDialog(this, "¿Desea modificar el registro?", "Modificación", 
                JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, botones, botones[0]);
        if(x==0){
            actualizar();
            mostrarEmpleados();
        }else{
           JOptionPane.showMessageDialog(this, "Proceso cancelado");
        }
    }//GEN-LAST:event_ModificarActionPerformed

    private void crearBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearBtnMousePressed
        // TODO add your handling code here:
        
        CrearEmpleado empleado = new CrearEmpleado();
        empleado.setSize(880, 430);
        empleado.setLocation(0, 0);
        
        crudPersonas.panel2.removeAll();
        crudPersonas.panel2.add(empleado, BorderLayout.CENTER);
        crudPersonas.panel2.revalidate();
        crudPersonas.panel2.repaint();
    }//GEN-LAST:event_crearBtnMousePressed

    private void crearBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearBtnMouseEntered
        // TODO add your handling code here:
        SetColores2 color = new SetColores2(crearBtn);
    }//GEN-LAST:event_crearBtnMouseEntered

    private void crearBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearBtnMouseExited
        // TODO add your handling code here:
        SetColores color = new SetColores(crearBtn);
    }//GEN-LAST:event_crearBtnMouseExited

    
    public void mostrarEmpleados(){
        DefaultTableModel modelo=new DefaultTableModel();
        Conexion cn=new Conexion();
        cn.Conectar();
        JTableHeader jtableheader = tablaEmpleado.getTableHeader();
        jtableheader.setDefaultRenderer(new PersonalizarTabla());
        
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("DPI");
        modelo.addColumn("Teléfono");
        modelo.addColumn("NIT");
        modelo.addColumn("IDPuesto");
        modelo.addColumn("Usuario");
        tablaEmpleado.setModel(modelo);
        String[] datos=new String[8];//depende de cuantas columnas queremos mostrar, igual si queremos
        //mostrar solamente 5campos de la BD el array sera de 5 y la tabla tendra solo 5 columnas
        
        //aquí se manda a traer a una vista que se ha creado en la BD
        try{

            String sql="call procedure_filtro_empleado('"+idTtx.getText()+"','"+nombreTxt.getText()+"')";
            cn.sentencia=cn.conexion.createStatement();
            cn.resultado=cn.sentencia.executeQuery(sql);
            //si el sql es correcto, ejecutrá el siguiente while
            while(cn.resultado.next()){
                //aquí se asignará a cada array el dato que corresponde
                datos[0]=cn.resultado.getString(1);
                datos[1]=cn.resultado.getString(2);
                datos[2]=cn.resultado.getString(3);
                datos[3]=cn.resultado.getString(4);
                datos[4]=cn.resultado.getString(5);
                datos[5]=cn.resultado.getString(6);
                datos[6]=cn.resultado.getString(7);
                datos[7]=cn.resultado.getString(8);
                modelo.addRow(datos);
            }
            tablaEmpleado.setModel(modelo);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error al conectar BD: "+e);
        }
    }
    
    public void actualizar(){
        int fila=tablaEmpleado.getSelectedRow();//la lía que está seleccionada
          String idTrabajador=tablaEmpleado.getValueAt(fila, 0).toString();
          String nombre=tablaEmpleado.getValueAt(fila, 1).toString();
          String apellido=tablaEmpleado.getValueAt(fila, 2).toString();
          long dpi=Long.parseLong(tablaEmpleado.getValueAt(fila, 3).toString());
          int telefono = Integer.parseInt(tablaEmpleado.getValueAt(fila, 4).toString());
          int nit = Integer.parseInt(tablaEmpleado.getValueAt(fila, 5).toString());
          int idPuesto = Integer.parseInt(tablaEmpleado.getValueAt(fila, 6).toString());
          String usuario=tablaEmpleado.getValueAt(fila, 7).toString();
          
          metodos.updateTrabajador(idTrabajador, nombre, apellido, dpi, telefono, nit, idPuesto, usuario);
    }
    
    public void eliminar(){
        int fila=tablaEmpleado.getSelectedRow();//la lía que está seleccionada
          String id=tablaEmpleado.getValueAt(fila, 0).toString();
          metodos.deleteTrabajador(id);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Eliminar;
    private javax.swing.JMenuItem Modificar;
    private javax.swing.JPanel crearBtn;
    private javax.swing.JTextField idTtx;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JPanel panel1;
    private javax.swing.JTable tablaEmpleado;
    // End of variables declaration//GEN-END:variables
}
