package crud;

import Metodos.Conexion;
import Metodos.PersonalizarTabla;
import Metodos.PersonalizarTabla2;
import Metodos.Placeholder;
import Metodos.SetColores;
import Metodos.SetColores2;
import Metodos.SetColores3;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author roger
 */
public class crudInventario extends javax.swing.JPanel {

    private int x=0;
    public crudInventario() {
        initComponents();
        filtroTxt.setVisible(false);
        filtro2Txt.setVisible(false);
        filtro21Txt.setVisible(false);
        filtro3Txt.setVisible(false);
        filtro31Txt.setVisible(false);
        
        //Ocultar separadores
        separador1.setVisible(false);
        separador2.setVisible(false);
        separador3.setVisible(false);
        separador4.setVisible(false);
        separador5.setVisible(false);
        
        //para los paneles
        SetColores3 color1 = new SetColores3(panel1);
        SetColores color2 = new SetColores(entradasBtn);
        SetColores color3 = new SetColores(salidasBtn);
        SetColores color4 = new SetColores(verProductoBtn);
        
        //para las cajas de texto
        SetColores3 ctxt1 = new SetColores3(filtroTxt);
        SetColores3 ctxt2 = new SetColores3(filtro2Txt);
        SetColores3 ctxt3 = new SetColores3(filtro21Txt);
        SetColores3 ctxt4 = new SetColores3(filtro3Txt);
        SetColores3 ctxt5 = new SetColores3(filtro31Txt);
        
        Placeholder caja1 = new Placeholder("Ingrese el producto a buscar", filtroTxt);
        Placeholder caja2 = new Placeholder("Buscar por Modelo", filtro21Txt);
        Placeholder caja3 = new Placeholder("Buscar por idCaracteristica", filtro2Txt);
        Placeholder caja4 = new Placeholder("Buscar por Modelo", filtro31Txt);
        Placeholder caja5 = new Placeholder("Buscar por idCaracteristica", filtro3Txt);
        
        PersonalizarTabla2 personalizar = new PersonalizarTabla2(tablaP);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        entradasBtn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        salidasBtn = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        verProductoBtn = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaP = new javax.swing.JTable();
        filtroTxt = new javax.swing.JTextField();
        filtro3Txt = new javax.swing.JTextField();
        filtro2Txt = new javax.swing.JTextField();
        filtro21Txt = new javax.swing.JTextField();
        filtro31Txt = new javax.swing.JTextField();
        separador5 = new javax.swing.JSeparator();
        separador4 = new javax.swing.JSeparator();
        separador3 = new javax.swing.JSeparator();
        separador2 = new javax.swing.JSeparator();
        separador1 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();

        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        entradasBtn.setBackground(new java.awt.Color(204, 204, 204));
        entradasBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        entradasBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        entradasBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                entradasBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                entradasBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                entradasBtnMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ver entradas");

        javax.swing.GroupLayout entradasBtnLayout = new javax.swing.GroupLayout(entradasBtn);
        entradasBtn.setLayout(entradasBtnLayout);
        entradasBtnLayout.setHorizontalGroup(
            entradasBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entradasBtnLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        entradasBtnLayout.setVerticalGroup(
            entradasBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entradasBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel1.add(entradasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 19, -1, -1));

        salidasBtn.setBackground(new java.awt.Color(204, 204, 204));
        salidasBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        salidasBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salidasBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salidasBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salidasBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                salidasBtnMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ver salidas");

        javax.swing.GroupLayout salidasBtnLayout = new javax.swing.GroupLayout(salidasBtn);
        salidasBtn.setLayout(salidasBtnLayout);
        salidasBtnLayout.setHorizontalGroup(
            salidasBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salidasBtnLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        salidasBtnLayout.setVerticalGroup(
            salidasBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salidasBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel1.add(salidasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 19, -1, -1));

        verProductoBtn.setBackground(new java.awt.Color(204, 204, 204));
        verProductoBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        verProductoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        verProductoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verProductoBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                verProductoBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                verProductoBtnMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ver Productos");

        javax.swing.GroupLayout verProductoBtnLayout = new javax.swing.GroupLayout(verProductoBtn);
        verProductoBtn.setLayout(verProductoBtnLayout);
        verProductoBtnLayout.setHorizontalGroup(
            verProductoBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verProductoBtnLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        verProductoBtnLayout.setVerticalGroup(
            verProductoBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verProductoBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel1.add(verProductoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(527, 19, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tablaP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaP.setShowGrid(true);
        jScrollPane1.setViewportView(tablaP);

        panel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 880, 330));

        filtroTxt.setBorder(null);
        filtroTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtroTxtActionPerformed(evt);
            }
        });
        panel1.add(filtroTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 200, 30));

        filtro3Txt.setBorder(null);
        filtro3Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtro3TxtActionPerformed(evt);
            }
        });
        panel1.add(filtro3Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 200, 30));

        filtro2Txt.setBorder(null);
        filtro2Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtro2TxtActionPerformed(evt);
            }
        });
        panel1.add(filtro2Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 200, 30));

        filtro21Txt.setBorder(null);
        filtro21Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtro21TxtActionPerformed(evt);
            }
        });
        panel1.add(filtro21Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 200, 30));

        filtro31Txt.setBorder(null);
        filtro31Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtro31TxtActionPerformed(evt);
            }
        });
        panel1.add(filtro31Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 200, 30));
        panel1.add(separador5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 200, -1));
        panel1.add(separador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 200, -1));
        panel1.add(separador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 200, -1));
        panel1.add(separador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 200, -1));
        panel1.add(separador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 200, -1));

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 20, 130));

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 20, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void verProductoBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verProductoBtnMousePressed
        // TODO add your handling code here:
        x=3;
        SetColores color2 = new SetColores(entradasBtn);
        SetColores color3 = new SetColores(salidasBtn);
        SetColores2 color4 = new SetColores2(verProductoBtn);
        
        filtro2Txt.setVisible(false);
        filtro21Txt.setVisible(false);
        filtro3Txt.setVisible(false);
        filtro31Txt.setVisible(false);
        //Separadores
        separador2.setVisible(false);
        separador3.setVisible(false);
        separador4.setVisible(false);
        separador5.setVisible(false);
        
        filtroTxt.setVisible(true);
        separador1.setVisible(true);
        
        mostrarProducto();
    }//GEN-LAST:event_verProductoBtnMousePressed

    private void filtroTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtroTxtActionPerformed
        // TODO add your handling code here:
        mostrarProducto();
    }//GEN-LAST:event_filtroTxtActionPerformed

    private void filtro3TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtro3TxtActionPerformed
        // TODO add your handling code here:
        mostrarEntradas();
    }//GEN-LAST:event_filtro3TxtActionPerformed

    private void filtro2TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtro2TxtActionPerformed
        // TODO add your handling code here:
        mostrarSalidas();
    }//GEN-LAST:event_filtro2TxtActionPerformed

    private void salidasBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salidasBtnMousePressed
        // TODO add your handling code here:
        x=1;
        SetColores color2 = new SetColores(entradasBtn);
        SetColores2 color3 = new SetColores2(salidasBtn);
        SetColores color4 = new SetColores(verProductoBtn);
        
        filtroTxt.setVisible(false);
        filtro3Txt.setVisible(false);
        filtro31Txt.setVisible(false);
        //Separadores
        separador1.setVisible(false);
        separador4.setVisible(false);
        separador5.setVisible(false);

        filtro2Txt.setVisible(true);
        filtro21Txt.setVisible(true);
        separador2.setVisible(true);
        separador3.setVisible(true);
        
        mostrarSalidas();
        
    }//GEN-LAST:event_salidasBtnMousePressed

    private void entradasBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entradasBtnMousePressed
        // TODO add your handling code here:
        x=2;
        SetColores2 color2 = new SetColores2(entradasBtn);
        SetColores color3 = new SetColores(salidasBtn);
        SetColores color4 = new SetColores(verProductoBtn);
        
        filtro2Txt.setVisible(false);
        filtro21Txt.setVisible(false);
        filtroTxt.setVisible(false);
        //Separadores
        separador1.setVisible(false);
        separador2.setVisible(false);
        separador3.setVisible(false);
        
        filtro3Txt.setVisible(true);
        filtro31Txt.setVisible(true);
        separador4.setVisible(true);
        separador5.setVisible(true);
        
        mostrarEntradas();
    }//GEN-LAST:event_entradasBtnMousePressed

    private void filtro21TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtro21TxtActionPerformed
        // TODO add your handling code here:

        mostrarSalidas();
    }//GEN-LAST:event_filtro21TxtActionPerformed

    private void filtro31TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtro31TxtActionPerformed
        // TODO add your handling code here:
        mostrarEntradas();
    }//GEN-LAST:event_filtro31TxtActionPerformed

    private void entradasBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entradasBtnMouseEntered
        // TODO add your handling code here:
        SetColores2 color = new SetColores2(entradasBtn);
    }//GEN-LAST:event_entradasBtnMouseEntered

    private void entradasBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entradasBtnMouseExited
        // TODO add your handling code here:
        if(x==2){
            
        }else{
            SetColores color = new SetColores(entradasBtn);
        }
    }//GEN-LAST:event_entradasBtnMouseExited

    private void salidasBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salidasBtnMouseEntered
        // TODO add your handling code here:
        SetColores2 color = new SetColores2(salidasBtn);
    }//GEN-LAST:event_salidasBtnMouseEntered

    private void salidasBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salidasBtnMouseExited
        // TODO add your handling code here:
        if(x==1){
            
        }else{
            SetColores color = new SetColores(salidasBtn);
        }
    }//GEN-LAST:event_salidasBtnMouseExited

    private void verProductoBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verProductoBtnMouseEntered
        // TODO add your handling code here:
        SetColores2 color = new SetColores2(verProductoBtn);
    }//GEN-LAST:event_verProductoBtnMouseEntered

    private void verProductoBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verProductoBtnMouseExited
        // TODO add your handling code here:
        if(x==3){
            
        }else{
        SetColores color = new SetColores(verProductoBtn);
        }
    }//GEN-LAST:event_verProductoBtnMouseExited

    
    public void mostrarProducto(){
        DefaultTableModel modelo=new DefaultTableModel();
        Conexion cn=new Conexion();
        cn.Conectar();
        JTableHeader jtableheader = tablaP.getTableHeader();
        jtableheader.setDefaultRenderer(new PersonalizarTabla());
        
        modelo.addColumn("Tipo");
        modelo.addColumn("Marca");
        modelo.addColumn("Modelo");
        modelo.addColumn("RAM");
        modelo.addColumn("ROM");
        modelo.addColumn("Color");
        modelo.addColumn("Ganancia %");
        modelo.addColumn("Precio");
        modelo.addColumn("Existencia");
        modelo.addColumn("Entradas");
        modelo.addColumn("Salidas");
        tablaP.setModel(modelo);
        String[] datos=new String[11];//depende de cuantas columnas queremos mostrar, igual si queremos
        //mostrar solamente 5campos de la BD el array sera de 5 y la tabla tendra solo 5 columnas
        
        //aquí se manda a traer a una vista que se ha creado en la BD
        try{
            String sql="call procedure_vista_GeneralProducto('"+filtroTxt.getText()+"')";
            cn.sentencia=cn.conexion.createStatement();
            cn.resultado=cn.sentencia.executeQuery(sql);
            //si el sql es correcto, ejecutrá el siguiente while
            while(cn.resultado.next()){
                //aquí se asignará a cada array el dato que corresponde
                datos[0]=cn.resultado.getString(1);
                datos[1]=cn.resultado.getString(2);
                datos[2]=cn.resultado.getString(3);
                datos[3]=cn.resultado.getString(4);
                datos[4]=cn.resultado.getString(5);
                datos[5]=cn.resultado.getString(6);
                datos[6]=cn.resultado.getString(7);
                datos[7]=cn.resultado.getString(8);
                datos[8]=cn.resultado.getString(9);
                datos[9]=cn.resultado.getString(10);
                datos[10]=cn.resultado.getString(11);
                modelo.addRow(datos);
            }
            tablaP.setModel(modelo);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erro BD: "+e);
        }
    }
    
    public void mostrarSalidas(){
        tablaP.removeAll();
        DefaultTableModel modelo=new DefaultTableModel();
        Conexion cn=new Conexion();
        cn.Conectar();
        
        modelo.addColumn("idDetalle");
        modelo.addColumn("idFactura");
        modelo.addColumn("Modelo");
        modelo.addColumn("idCaracteristica");
        modelo.addColumn("Cantidad");
        modelo.addColumn("cantidadxPrecio");
        modelo.addColumn("Fecha");
        tablaP.setModel(modelo);
        String[] datos=new String[7];//depende de cuantas columnas queremos mostrar, igual si queremos
        //mostrar solamente 5campos de la BD el array sera de 5 y la tabla tendra solo 5 columnas
        
        //aquí se manda a traer a una vista que se ha creado en la BD
        try{

            String sql="call procedure_vista_salidas('"+filtro21Txt.getText()+"','"+filtro2Txt.getText()+"')";
            cn.sentencia=cn.conexion.createStatement();
            cn.resultado=cn.sentencia.executeQuery(sql);
            //si el sql es correcto, ejecutrá el siguiente while
            while(cn.resultado.next()){
                //aquí se asignará a cada array el dato que corresponde
                datos[0]=cn.resultado.getString(1);
                datos[1]=cn.resultado.getString(2);
                datos[2]=cn.resultado.getString(3);
                datos[3]=cn.resultado.getString(4);
                datos[4]=cn.resultado.getString(5);
                datos[5]=cn.resultado.getString(6);
                datos[6]=cn.resultado.getString(7);
                modelo.addRow(datos);
            }
            tablaP.setModel(modelo);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erro BD: "+e);
        }
    }
    
     public void mostrarEntradas(){
        DefaultTableModel modelo=new DefaultTableModel();
        Conexion cn=new Conexion();
        cn.Conectar();
        
        modelo.addColumn("idDetalle");
        modelo.addColumn("idFactura");
        modelo.addColumn("Proveedor");
        modelo.addColumn("Fecha");
        modelo.addColumn("idCaracteristica");
        modelo.addColumn("Modelo");
        modelo.addColumn("Precio");
        modelo.addColumn("Cantidad");
        modelo.addColumn("cantidadxPrecio");
        tablaP.setModel(modelo);
        String[] datos=new String[9];//depende de cuantas columnas queremos mostrar, igual si queremos
        //mostrar solamente 5campos de la BD el array sera de 5 y la tabla tendra solo 5 columnas
        
        //aquí se manda a traer a una vista que se ha creado en la BD
        try{

            String sql="call procedure_vista_entradas('"+filtro31Txt.getText()+"','"+filtro3Txt.getText()+"')";
            cn.sentencia=cn.conexion.createStatement();
            cn.resultado=cn.sentencia.executeQuery(sql);
            //si el sql es correcto, ejecutrá el siguiente while
            while(cn.resultado.next()){
                //aquí se asignará a cada array el dato que corresponde
                datos[0]=cn.resultado.getString(1);
                datos[1]=cn.resultado.getString(2);
                datos[2]=cn.resultado.getString(3);
                datos[3]=cn.resultado.getString(4);
                datos[4]=cn.resultado.getString(5);
                datos[5]=cn.resultado.getString(6);
                datos[6]=cn.resultado.getString(7);
                datos[7]=cn.resultado.getString(8);
                datos[8]=cn.resultado.getString(9);
                modelo.addRow(datos);
            }
            tablaP.setModel(modelo);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erro BD: "+e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel entradasBtn;
    private javax.swing.JTextField filtro21Txt;
    private javax.swing.JTextField filtro2Txt;
    private javax.swing.JTextField filtro31Txt;
    private javax.swing.JTextField filtro3Txt;
    private javax.swing.JTextField filtroTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel salidasBtn;
    private javax.swing.JSeparator separador1;
    private javax.swing.JSeparator separador2;
    private javax.swing.JSeparator separador3;
    private javax.swing.JSeparator separador4;
    private javax.swing.JSeparator separador5;
    private javax.swing.JTable tablaP;
    private javax.swing.JPanel verProductoBtn;
    // End of variables declaration//GEN-END:variables
}
