/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crud;

import Metodos.Conexion;
import Metodos.MetodosBD2;
import Metodos.PersonalizarTabla;
import Metodos.PersonalizarTabla2;
import Metodos.Placeholder;
import Metodos.SetColores;
import Metodos.SetColores2;
import Metodos.SetColores3;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author roger
 */
public class CrudTipoProducto extends javax.swing.JPanel {

    
    MetodosBD2 metodos = new MetodosBD2();
    String [] botones = {"Aceptar", "Cancelar"}; //Para botones de opciones de los JOption Pane.showOptionDialog
    
    public CrudTipoProducto() {
        initComponents();
        mostrarTipos();
        
        SetColores3 color1 = new SetColores3(panel1);
        
        SetColores3 ctx1 = new SetColores3(idTipoTxt);
        SetColores3 ctx2 = new SetColores3(tipoTxt);
        
        Placeholder caja1 = new Placeholder("Ingrese el nuevo ID Tipo.",idTipoTxt);
        Placeholder caja2 = new Placeholder("Ingrese el tipo de producto",tipoTxt);
        
        PersonalizarTabla2 personalizar = new PersonalizarTabla2(tipoTabla);
        metodos.verItem(actualizarItem, eliminarItem);
        metodos.verBoton(guardarBtn);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        actualizarItem = new javax.swing.JMenuItem();
        eliminarItem = new javax.swing.JMenuItem();
        panel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tipoTabla = new javax.swing.JTable();
        idTipoTxt = new javax.swing.JTextField();
        tipoTxt = new javax.swing.JTextField();
        guardarBtn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        actualizarItem.setText("Modificar");
        actualizarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarItemActionPerformed(evt);
            }
        });
        jPopupMenu1.add(actualizarItem);

        eliminarItem.setText("Eliminar");
        eliminarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarItemActionPerformed(evt);
            }
        });
        jPopupMenu1.add(eliminarItem);

        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tipoTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tipoTabla.setComponentPopupMenu(jPopupMenu1);
        tipoTabla.setShowGrid(true);
        jScrollPane1.setViewportView(tipoTabla);

        panel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 650, 250));

        idTipoTxt.setBorder(null);
        panel1.add(idTipoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 140, 20));

        tipoTxt.setBorder(null);
        tipoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoTxtActionPerformed(evt);
            }
        });
        panel1.add(tipoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 220, 20));

        guardarBtn.setBackground(new java.awt.Color(153, 153, 153));
        guardarBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        guardarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guardarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                guardarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                guardarBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                guardarBtnMousePressed(evt);
            }
        });
        guardarBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Guardar");
        guardarBtn.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        panel1.add(guardarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 160, 40));
        panel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 140, -1));
        panel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 220, 10));

        jLabel2.setText("ID.");
        panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        jLabel3.setText("Tipo de producto");
        panel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tipoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoTxtActionPerformed

    private void guardarBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarBtnMousePressed
        // TODO add your handling code here:
        metodos.insertTipoProducto(idTipoTxt.getText(), tipoTxt.getText());
        mostrarTipos();
        idTipoTxt.setText("");
        tipoTxt.setText("");
    }//GEN-LAST:event_guardarBtnMousePressed

    private void actualizarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarItemActionPerformed
        // TODO add your handling code here:
        int x=JOptionPane.showOptionDialog(this, "¿Desea modificar el registro?", "Modificación", 
                JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, botones, botones[0]);
        if(x==0){
            actualizar();
            mostrarTipos();
        }else{
           JOptionPane.showMessageDialog(this, "Proceso cancelado");
        }
    }//GEN-LAST:event_actualizarItemActionPerformed

    private void eliminarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarItemActionPerformed
        // TODO add your handling code here:
        int x=JOptionPane.showOptionDialog(this, "¿Desea eliminar el registro?", "Eliminación", 
                JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, botones, botones[0]);
        if(x==0){
            eliminar();
            mostrarTipos();
        }else{
           JOptionPane.showMessageDialog(this, "Proceso cancelado");
        }
        
    }//GEN-LAST:event_eliminarItemActionPerformed

    private void guardarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarBtnMouseEntered
        // TODO add your handling code here:
         SetColores2 color = new SetColores2(guardarBtn);
    }//GEN-LAST:event_guardarBtnMouseEntered

    private void guardarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarBtnMouseExited
        // TODO add your handling code here:
        SetColores color = new SetColores(guardarBtn);
    }//GEN-LAST:event_guardarBtnMouseExited

    public void mostrarTipos(){
        DefaultTableModel modelo=new DefaultTableModel();
        Conexion cn=new Conexion();
        cn.Conectar();
        JTableHeader jtableheader = tipoTabla.getTableHeader();
        jtableheader.setDefaultRenderer(new PersonalizarTabla());
        
        modelo.addColumn("IdTipo");
        modelo.addColumn("Tipos de Productos");
        tipoTabla.setModel(modelo);
        String[] datos=new String[2];//depende de cuantas columnas queremos mostrar, igual si queremos
        //mostrar solamente 5campos de la BD el array sera de 5 y la tabla tendra solo 5 columnas
        
        //aquí se manda a traer a una vista que se ha creado en la BD
        try{

            String sql="select *from tipoproducto";
            cn.sentencia=cn.conexion.createStatement();
            cn.resultado=cn.sentencia.executeQuery(sql);
            //si el sql es correcto, ejecutrá el siguiente while
            while(cn.resultado.next()){
                //aquí se asignará a cada array el dato que corresponde
                datos[0]=cn.resultado.getString(1);
                datos[1]=cn.resultado.getString(2);
                modelo.addRow(datos);
            }
            tipoTabla.setModel(modelo);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erro BD: "+e);
        }
    }
    
    public void actualizar(){
        int fila=tipoTabla.getSelectedRow();//la lía que está seleccionada
        
        String id=tipoTabla.getValueAt(fila, 0).toString();
        String tipo=tipoTabla.getValueAt(fila, 1).toString();
        metodos.updateTipoProducto(id, tipo);
    }
    
    public void eliminar(){
        int fila=tipoTabla.getSelectedRow();//la lía que está seleccionada
        
        String id=tipoTabla.getValueAt(fila, 0).toString();
        metodos.deleteTipoProducto(id);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem actualizarItem;
    private javax.swing.JMenuItem eliminarItem;
    private javax.swing.JPanel guardarBtn;
    private javax.swing.JTextField idTipoTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel panel1;
    private javax.swing.JTable tipoTabla;
    private javax.swing.JTextField tipoTxt;
    // End of variables declaration//GEN-END:variables
}
