package crud;

import Metodos.Conexion;
import Metodos.MetodosBD2;
import Metodos.PersonalizarTabla;
import Metodos.PersonalizarTabla2;
import Metodos.Placeholder;
import Metodos.SetColores;
import Metodos.SetColores2;
import Metodos.SetColores3;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;


public class CrudClientes extends javax.swing.JPanel {

    MetodosBD2 metodos = new MetodosBD2();
    String [] botones = {"Aceptar", "Cancelar"}; //Para botones de opciones de los JOption Pane.showOptionDialog
    
    public CrudClientes() {
        initComponents();
        mostrarClientes();
        
        SetColores3 color1 = new SetColores3(panel1);
        SetColores color2 = new SetColores(crearBtn);
        
        Placeholder caja = new Placeholder("Cliente a buscar",buscarTxt);
        SetColores3 ctxt = new SetColores3(buscarTxt);
        
        PersonalizarTabla2 personalizar = new PersonalizarTabla2(tablaClientes);
        
        metodos.verItem(modificarItem, eliminarItem);
        metodos.verBoton(crearBtn);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        modificarItem = new javax.swing.JMenuItem();
        eliminarItem = new javax.swing.JMenuItem();
        panel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        buscarTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        crearBtn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        modificarItem.setText("Modificar");
        modificarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarItemActionPerformed(evt);
            }
        });
        jPopupMenu1.add(modificarItem);

        eliminarItem.setText("Eliminar");
        eliminarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarItemActionPerformed(evt);
            }
        });
        jPopupMenu1.add(eliminarItem);

        setPreferredSize(new java.awt.Dimension(880, 420));

        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaClientes.setComponentPopupMenu(jPopupMenu1);
        tablaClientes.setShowGrid(true);
        jScrollPane1.setViewportView(tablaClientes);

        panel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 880, 280));

        buscarTxt.setBorder(null);
        buscarTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarTxtActionPerformed(evt);
            }
        });
        panel1.add(buscarTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 190, 30));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 10, 120));

        crearBtn.setBackground(new java.awt.Color(102, 102, 102));
        crearBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        crearBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        crearBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                crearBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                crearBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                crearBtnMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Crear nuevo cliente");

        javax.swing.GroupLayout crearBtnLayout = new javax.swing.GroupLayout(crearBtn);
        crearBtn.setLayout(crearBtnLayout);
        crearBtnLayout.setHorizontalGroup(
            crearBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearBtnLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );
        crearBtnLayout.setVerticalGroup(
            crearBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        panel1.add(crearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 170, 30));
        panel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 190, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buscarTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarTxtActionPerformed

    private void eliminarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarItemActionPerformed
        // TODO add your handling code here:
        int x=JOptionPane.showOptionDialog(this, "¿Desea eliminar el registro?", "Modificación", 
                JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, botones, botones[0]);
        if(x==0){
            eliminar();
            mostrarClientes();
        }else{
           JOptionPane.showMessageDialog(this, "Proceso cancelado");
        }
    }//GEN-LAST:event_eliminarItemActionPerformed

    private void modificarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarItemActionPerformed
        // TODO add your handling code here:
        int x=JOptionPane.showOptionDialog(this, "¿Desea modificar el registro?", "Modificación", 
                JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, botones, botones[0]);
        if(x==0){
            actualizar();
            mostrarClientes();
        }else{
           JOptionPane.showMessageDialog(this, "Proceso cancelado");
        }
    }//GEN-LAST:event_modificarItemActionPerformed

    private void crearBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearBtnMousePressed
        // TODO add your handling code here:
        CrearCliente cliente = new CrearCliente();
        cliente.setSize(880, 430);
        cliente.setLocation(0, 0);
        
        //tuve que hacer que el panel2 de la clase crudPersona fuera publica y static
        crudPersonas.panel2.removeAll();
        crudPersonas.panel2.add(cliente, BorderLayout.CENTER);
        crudPersonas.panel2.revalidate();
        crudPersonas.panel2.repaint();
    }//GEN-LAST:event_crearBtnMousePressed

    private void crearBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearBtnMouseEntered
        // TODO add your handling code here:
        SetColores2 color = new SetColores2(crearBtn);
    }//GEN-LAST:event_crearBtnMouseEntered

    private void crearBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearBtnMouseExited
        // TODO add your handling code here:
        SetColores color = new SetColores(crearBtn);
    }//GEN-LAST:event_crearBtnMouseExited

    public void mostrarClientes(){
        DefaultTableModel modelo=new DefaultTableModel();
        Conexion cn=new Conexion();
        cn.Conectar();
        
        JTableHeader jtableheader = tablaClientes.getTableHeader();
        jtableheader.setDefaultRenderer(new PersonalizarTabla());
        
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("NIT");
        modelo.addColumn("Direccion");
        modelo.addColumn("Usuario");
        modelo.addColumn("Género");
        tablaClientes.setModel(modelo);
        String[] datos=new String[7];//depende de cuantas columnas queremos mostrar, igual si queremos
        //mostrar solamente 5campos de la BD el array sera de 5 y la tabla tendra solo 5 columnas
        
        //aquí se manda a traer a una vista que se ha creado en la BD
        try{

            String sql="call procedure_filtro_clientes('"+buscarTxt.getText()+"')";
            cn.sentencia=cn.conexion.createStatement();
            cn.resultado=cn.sentencia.executeQuery(sql);
            //si el sql es correcto, ejecutrá el siguiente while
            while(cn.resultado.next()){
                //aquí se asignará a cada array el dato que corresponde
                datos[0]=cn.resultado.getString(1);
                datos[1]=cn.resultado.getString(2);
                datos[2]=cn.resultado.getString(3);
                datos[3]=cn.resultado.getString(4);
                datos[4]=cn.resultado.getString(5);
                datos[5]=cn.resultado.getString(6);
                datos[6]=cn.resultado.getString(7);
                modelo.addRow(datos);
            }
            tablaClientes.setModel(modelo);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error al conectar BD: "+e);
        }
    }
    
    public void actualizar(){
        int fila=tablaClientes.getSelectedRow();//la lía que está seleccionada
          String id=tablaClientes.getValueAt(fila, 0).toString();
          String nombre=tablaClientes.getValueAt(fila, 1).toString();
          String apellido=tablaClientes.getValueAt(fila, 2).toString();
          String nit=tablaClientes.getValueAt(fila, 3).toString();
          String direccion=tablaClientes.getValueAt(fila, 4).toString();
          String usuario=tablaClientes.getValueAt(fila, 5).toString();
          String genero=tablaClientes.getValueAt(fila, 6).toString();
          
          metodos.updateCliente(id, nombre, apellido, nit, direccion, genero);   
    }
    
    public void eliminar(){
        int fila=tablaClientes.getSelectedRow();//la lía que está seleccionada
          String id=tablaClientes.getValueAt(fila, 0).toString();
          metodos.deleteCliente(id);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buscarTxt;
    private javax.swing.JPanel crearBtn;
    private javax.swing.JMenuItem eliminarItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JMenuItem modificarItem;
    private javax.swing.JPanel panel1;
    private javax.swing.JTable tablaClientes;
    // End of variables declaration//GEN-END:variables
}
