package crud;

import Metodos.SetColores;
import Metodos.SetColores2;
import Metodos.SetColores3;
import java.awt.BorderLayout;


public class crudProductos extends javax.swing.JPanel {

   private int x=0;
    public crudProductos() {
        initComponents();
        
        SetColores3 color1 = new SetColores3(panel1);
        SetColores3 color2 = new SetColores3(panel2);
        SetColores color3 = new SetColores(marcaBtn);
        SetColores color4 = new SetColores(productoBtn);
        SetColores color5 = new SetColores(caracteristicaBtn);
        SetColores color6 = new SetColores(tipoBtn);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel1 = new javax.swing.JPanel();
        tipoBtn = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        caracteristicaBtn = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        marcaBtn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        productoBtn = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panel2 = new javax.swing.JPanel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setBackground(new java.awt.Color(204, 204, 204));
        panel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tipoBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tipoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tipoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tipoBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tipoBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tipoBtnMousePressed(evt);
            }
        });
        tipoBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tipo Producto");
        tipoBtn.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 6, -1, -1));

        panel1.add(tipoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 160, 50));

        caracteristicaBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        caracteristicaBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        caracteristicaBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                caracteristicaBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                caracteristicaBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                caracteristicaBtnMousePressed(evt);
            }
        });
        caracteristicaBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Caracteristicas");
        caracteristicaBtn.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        panel1.add(caracteristicaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 160, 50));

        marcaBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        marcaBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        marcaBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                marcaBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                marcaBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                marcaBtnMousePressed(evt);
            }
        });
        marcaBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Marcas");
        marcaBtn.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 60, -1));

        panel1.add(marcaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 160, 50));
        panel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 10));

        productoBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        productoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        productoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                productoBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                productoBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                productoBtnMousePressed(evt);
            }
        });
        productoBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Producto");
        productoBtn.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        panel1.add(productoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 160, 50));

        jPanel1.add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 70));

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        jPanel1.add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 880, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void marcaBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marcaBtnMousePressed
        // TODO add your handling code here:
        x=1;
        SetColores2 color3 = new SetColores2(marcaBtn);
        SetColores color4 = new SetColores(productoBtn);
        SetColores color5 = new SetColores(caracteristicaBtn);
        SetColores color6 = new SetColores(tipoBtn);
        
        crudMarcas marca=new crudMarcas();
        marca.setSize(880,610);
        marca.setLocation(0,0);
        
        panel2.removeAll();
        panel2.add(marca,BorderLayout.CENTER);
        panel2.revalidate();
        panel2.repaint();
    }//GEN-LAST:event_marcaBtnMousePressed

    private void productoBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productoBtnMousePressed
        // TODO add your handling code here:
        x=2;
        SetColores color3 = new SetColores(marcaBtn);
        SetColores2 color4 = new SetColores2(productoBtn);
        SetColores color5 = new SetColores(caracteristicaBtn);
        SetColores color6 = new SetColores(tipoBtn);
        
        CrudProductoTabla p=new CrudProductoTabla();
        p.setSize(880,610);
        p.setLocation(0,0);
        
        panel2.removeAll();
        panel2.add(p,BorderLayout.CENTER);
        panel2.revalidate();
        panel2.repaint();
        
    }//GEN-LAST:event_productoBtnMousePressed

    private void caracteristicaBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caracteristicaBtnMousePressed
        // TODO add your handling code here:
        x=3;
        SetColores color3 = new SetColores(marcaBtn);
        SetColores color4 = new SetColores(productoBtn);
        SetColores2 color5 = new SetColores2(caracteristicaBtn);
        SetColores color6 = new SetColores(tipoBtn);
        
        crudCarcateristica p=new crudCarcateristica();
        p.setSize(880,610);
        p.setLocation(0,0);
        
        panel2.removeAll();
        panel2.add(p,BorderLayout.CENTER);
        panel2.revalidate();
        panel2.repaint();
    }//GEN-LAST:event_caracteristicaBtnMousePressed

    private void tipoBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tipoBtnMousePressed
        // TODO add your handling code here:
        x=3;
        SetColores color3 = new SetColores(marcaBtn);
        SetColores color4 = new SetColores(productoBtn);
        SetColores color5 = new SetColores(caracteristicaBtn);
        SetColores2 color6 = new SetColores2(tipoBtn);
        
        CrudTipoProducto p=new CrudTipoProducto();
        p.setSize(880,610);
        p.setLocation(0,0);
        
        panel2.removeAll();
        panel2.add(p,BorderLayout.CENTER);
        panel2.revalidate();
        panel2.repaint();
    }//GEN-LAST:event_tipoBtnMousePressed

    private void marcaBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marcaBtnMouseEntered
        // TODO add your handling code here:
        SetColores2 color = new SetColores2(marcaBtn);
    }//GEN-LAST:event_marcaBtnMouseEntered

    private void marcaBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marcaBtnMouseExited
        // TODO add your handling code here:
        if(x==1){
            //no hace nada ya que quiero que el boton siga del mismo color al ser seleccionado
        }else{
            SetColores color = new SetColores(marcaBtn);
        }
    }//GEN-LAST:event_marcaBtnMouseExited

    private void productoBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productoBtnMouseEntered
        // TODO add your handling code here:
        SetColores2 color = new SetColores2(productoBtn);
    }//GEN-LAST:event_productoBtnMouseEntered

    private void productoBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productoBtnMouseExited
        // TODO add your handling code here:
        if(x==2){
            //no hace nada ya que quiero que el boton siga del mismo color al ser seleccionado
        }else{
            SetColores color = new SetColores(productoBtn);
        }
    }//GEN-LAST:event_productoBtnMouseExited

    private void caracteristicaBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caracteristicaBtnMouseEntered
        // TODO add your handling code here:
        SetColores2 color = new SetColores2(caracteristicaBtn);
    }//GEN-LAST:event_caracteristicaBtnMouseEntered

    private void caracteristicaBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caracteristicaBtnMouseExited
        // TODO add your handling code here:
        if(x==3){
            //no hace nada ya que quiero que el boton siga del mismo color al ser seleccionado
        }else{
            SetColores color = new SetColores(caracteristicaBtn);
        }
    }//GEN-LAST:event_caracteristicaBtnMouseExited

    private void tipoBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tipoBtnMouseEntered
        // TODO add your handling code here:
        SetColores2 color = new SetColores2(tipoBtn);
    }//GEN-LAST:event_tipoBtnMouseEntered

    private void tipoBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tipoBtnMouseExited
        // TODO add your handling code here:
        if(x==4){
            //no hace nada ya que quiero que el boton siga del mismo color al ser seleccionado
        }else{
            SetColores color = new SetColores(tipoBtn);
        }
    }//GEN-LAST:event_tipoBtnMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel caracteristicaBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel marcaBtn;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel productoBtn;
    private javax.swing.JPanel tipoBtn;
    // End of variables declaration//GEN-END:variables
}
