/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crud;

import Metodos.Conexion;
import Metodos.Fondos;
import Metodos.MetodosBD2;
import Metodos.PersonalizarTabla;
import Metodos.PersonalizarTabla2;
import Metodos.Placeholder;
import Metodos.SetColores;
import Metodos.SetColores2;
import Metodos.SetColores3;
import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.Blob;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.BevelBorder;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author roger
 */
public class CrudProductoTabla extends javax.swing.JPanel {

    String ruta;
    MetodosBD2 metodos = new MetodosBD2();
    String [] botones = {"Aceptar", "Cancelar"}; //Para botones de opciones de los JOption Pane.showOptionDialog
    
    public CrudProductoTabla() {
        initComponents();
        mostrarProductos();
        
        SetColores3 color1 = new SetColores3(panel1);
        SetColores color2 = new SetColores(guardarBtn);
        SetColores color3 = new SetColores(abritBtn);
        
        SetColores3 ctxt1 = new SetColores3(idPTxt);
        SetColores3 ctxt2 = new SetColores3(idMarcaTxt);
        SetColores3 ctxt3 = new SetColores3(modeloTxt);
        SetColores3 ctxt4 = new SetColores3(tipoTxt);
        
        Placeholder caja1 = new Placeholder("Ingrese el ID producto", idPTxt);
        Placeholder caja2 = new Placeholder("Ingrese el Id marca", idMarcaTxt);
        Placeholder caja3 = new Placeholder("Ingrese el modelo", modeloTxt);
        Placeholder caja4 = new Placeholder("Ingrese el id Tipo de procuto", tipoTxt);
        
        PersonalizarTabla2 personalizar = new PersonalizarTabla2(tablaP);
        
        metodos.verItem(actualizarItem, eliminarItem);
        metodos.verBoton(guardarBtn);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        actualizarItem = new javax.swing.JMenuItem();
        eliminarItem = new javax.swing.JMenuItem();
        panel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaP = new javax.swing.JTable();
        idPTxt = new javax.swing.JTextField();
        idMarcaTxt = new javax.swing.JTextField();
        modeloTxt = new javax.swing.JTextField();
        tipoTxt = new javax.swing.JTextField();
        abritBtn = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        urlLabel = new javax.swing.JLabel();
        guardarBtn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        imagenLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        actualizarItem.setText("Modificar");
        actualizarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarItemActionPerformed(evt);
            }
        });
        jPopupMenu1.add(actualizarItem);

        eliminarItem.setText("Eliminar");
        eliminarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarItemActionPerformed(evt);
            }
        });
        jPopupMenu1.add(eliminarItem);

        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaP.setComponentPopupMenu(jPopupMenu1);
        tablaP.setShowGrid(true);
        jScrollPane1.setViewportView(tablaP);

        panel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 660, 320));

        idPTxt.setBorder(null);
        idPTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idPTxtActionPerformed(evt);
            }
        });
        panel1.add(idPTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 170, 20));

        idMarcaTxt.setBorder(null);
        panel1.add(idMarcaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 170, 20));

        modeloTxt.setBorder(null);
        panel1.add(modeloTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 170, 20));

        tipoTxt.setBorder(null);
        tipoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoTxtActionPerformed(evt);
            }
        });
        panel1.add(tipoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 170, 20));

        abritBtn.setBackground(new java.awt.Color(102, 102, 102));
        abritBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        abritBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        abritBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                abritBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                abritBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                abritBtnMousePressed(evt);
            }
        });
        abritBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Abrir explorador");
        abritBtn.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 30));

        panel1.add(abritBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 170, 30));

        urlLabel.setForeground(new java.awt.Color(153, 153, 153));
        panel1.add(urlLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 180, 20));

        guardarBtn.setBackground(new java.awt.Color(102, 102, 102));
        guardarBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        guardarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guardarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                guardarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                guardarBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                guardarBtnMousePressed(evt);
            }
        });
        guardarBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Guardar nuevo producto");
        guardarBtn.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        panel1.add(guardarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 160, 40));
        panel1.add(imagenLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 170, 130));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 10, 90));
        panel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 170, -1));
        panel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 170, 10));
        panel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 170, 10));
        panel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 170, 10));

        jLabel3.setText("Id nuevo Producto");
        panel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        jLabel4.setText("ID Marca ");
        panel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel5.setText("Modelo");
        panel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel6.setText("ID tipo");
        panel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void idPTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idPTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idPTxtActionPerformed

    private void tipoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoTxtActionPerformed

    private void abritBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abritBtnMousePressed
        // TODO add your handling code here:
        JFileChooser jfile = new JFileChooser();
        int ap=jfile.showOpenDialog(this);
        if(ap == JFileChooser.APPROVE_OPTION){//si seleccionamos una imagene entonces hará lo siguiente:
            ruta = jfile.getSelectedFile().getAbsolutePath();//se obtiene la ruta de imagenen
            Image miimagen=new ImageIcon(ruta).getImage();
            ImageIcon miIcono = new ImageIcon(miimagen.getScaledInstance(imagenLabel.getWidth(), imagenLabel.getHeight(), 0));
            imagenLabel.setIcon(miIcono);
            urlLabel.setText(ruta);
        }
    }//GEN-LAST:event_abritBtnMousePressed

    private void guardarBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarBtnMousePressed
        // TODO add your handling code here:
        MetodosBD2 metodos = new MetodosBD2();
        metodos.insertProducto(idPTxt.getText(), Integer.parseInt(idMarcaTxt.getText()), modeloTxt.getText(), 
                ruta, tipoTxt.getText());
        mostrarProductos();
        idPTxt.setText("");
        idMarcaTxt.setText("");
        modeloTxt.setText("");
        tipoTxt.setText("");
        imagenLabel.removeAll();
        imagenLabel.setText("");
        ruta="";
        urlLabel.setText("");
    }//GEN-LAST:event_guardarBtnMousePressed

    private void actualizarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarItemActionPerformed
        // TODO add your handling code here:
        int x=JOptionPane.showOptionDialog(this, "¿Desea modificar el registro?", "Modificación", 
                JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, botones, botones[0]);
        if(x==0){
            actualizar();
            mostrarProductos();
        }else{
           JOptionPane.showMessageDialog(this, "Proceso cancelado");
        }
    }//GEN-LAST:event_actualizarItemActionPerformed

    private void eliminarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarItemActionPerformed
        // TODO add your handling code here:
        int x=JOptionPane.showOptionDialog(this, "¿Desea eliminar el registro?", "Eliminación", 
                JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, botones, botones[0]);
        if(x==0){
            eliminar();
            mostrarProductos();
        }else{
           JOptionPane.showMessageDialog(this, "Proceso cancelado");
        }
    }//GEN-LAST:event_eliminarItemActionPerformed

    private void guardarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarBtnMouseEntered
        // TODO add your handling code here:
        SetColores2 color2 = new SetColores2(guardarBtn);
    }//GEN-LAST:event_guardarBtnMouseEntered

    private void guardarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarBtnMouseExited
        // TODO add your handling code here:
        SetColores color2 = new SetColores(guardarBtn);
    }//GEN-LAST:event_guardarBtnMouseExited

    private void abritBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abritBtnMouseEntered
        // TODO add your handling code here:
        SetColores2 color2 = new SetColores2(abritBtn);
    }//GEN-LAST:event_abritBtnMouseEntered

    private void abritBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abritBtnMouseExited
        // TODO add your handling code here:
        SetColores color2 = new SetColores(abritBtn);
    }//GEN-LAST:event_abritBtnMouseExited
        
    public void mostrarProductos(){
        DefaultTableModel modelo=new DefaultTableModel();
        Conexion cn=new Conexion();
        cn.Conectar();
        JTableHeader jtableheader = tablaP.getTableHeader();
        jtableheader.setDefaultRenderer(new PersonalizarTabla());
        
        tablaP.setDefaultRenderer(Object.class, new TablaImagenProducto());

        
        modelo.addColumn("idProducto");
        modelo.addColumn("idMarca");
        modelo.addColumn("Modelo");
        modelo.addColumn("Imagen");
        modelo.addColumn("Tipo");
        tablaP.setModel(modelo);
        tablaP.setRowHeight(90);
        try{
            String sql="select *from producto";
            cn.sentencia=cn.conexion.createStatement();
            cn.resultado=cn.sentencia.executeQuery(sql);
            //si el sql es correcto, ejecutrá el siguiente while
            
            while(cn.resultado.next()){
                //aquí se asignará a cada array el dato que corresponde
                Object[] datos = new Object[5];
                datos[0] = cn.resultado.getObject(1);
                datos[1] = cn.resultado.getObject(2);
                datos[2] = cn.resultado.getObject(3);
                
                Blob blob = cn.resultado.getBlob(4);
                
                if(blob != null){
                    try{
                        byte[] data = blob.getBytes(1, (int)blob.length());
                        BufferedImage img=null;
                        try{
                            img=ImageIO.read(new ByteArrayInputStream(data));
                        }catch(Exception e){
                            JOptionPane.showMessageDialog(null, "Error en imagen:"+e);
                        }
                                                
                        ImageIcon icono = new ImageIcon(img.getScaledInstance(70, 60, 0));
                        datos[3] = new JLabel(icono);
                    }catch(Exception e){
                        datos[3] = "No imagen";
                    }
                }else{
                    datos[3]="No imagen";
                }
                datos[4] = cn.resultado.getObject(5);
                modelo.addRow(datos);
            }
            tablaP.setModel(modelo);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erro BD: "+e);
        }
    }
    
    public void actualizar(){
        int fila=tablaP.getSelectedRow();//la lía que está seleccionada
        
        String id=tablaP.getValueAt(fila, 0).toString();
        int marca=Integer.parseInt(tablaP.getValueAt(fila, 1).toString());
        String modelo = tablaP.getValueAt(fila, 2).toString();
        String tipo = tablaP.getValueAt(fila, 4).toString();
        metodos.updateProducto(id, marca, modelo, tipo);
    }
    
    public void eliminar(){
        int fila=tablaP.getSelectedRow();//la lía que está seleccionada
        
        String id=tablaP.getValueAt(fila, 0).toString();
        metodos.deleteProducto(id);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel abritBtn;
    private javax.swing.JMenuItem actualizarItem;
    private javax.swing.JMenuItem eliminarItem;
    private javax.swing.JPanel guardarBtn;
    private javax.swing.JTextField idMarcaTxt;
    private javax.swing.JTextField idPTxt;
    private javax.swing.JLabel imagenLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField modeloTxt;
    private javax.swing.JPanel panel1;
    private javax.swing.JTable tablaP;
    private javax.swing.JTextField tipoTxt;
    private javax.swing.JLabel urlLabel;
    // End of variables declaration//GEN-END:variables
}
