package crud;

import Metodos.SetColores;
import Metodos.SetColores2;
import Metodos.SetColores3;
import java.awt.BorderLayout;


public class CrudEmpresa extends javax.swing.JPanel {

    private int x=0;
    
    public CrudEmpresa() {
        initComponents();
        
        SetColores3 color1 = new SetColores3(panel1);
        SetColores3 color2 = new SetColores3(panel2);
        SetColores color3 = new SetColores(proveedoresBtn);
        SetColores color4 = new SetColores(puestosBtn);
        SetColores color5 = new SetColores(deptBtn);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel1 = new javax.swing.JPanel();
        puestosBtn = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        proveedoresBtn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        deptBtn = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        panel2 = new javax.swing.JPanel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setBackground(new java.awt.Color(204, 204, 204));
        panel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        puestosBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        puestosBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        puestosBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                puestosBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                puestosBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                puestosBtnMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Puestos");

        javax.swing.GroupLayout puestosBtnLayout = new javax.swing.GroupLayout(puestosBtn);
        puestosBtn.setLayout(puestosBtnLayout);
        puestosBtnLayout.setHorizontalGroup(
            puestosBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, puestosBtnLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        puestosBtnLayout.setVerticalGroup(
            puestosBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(puestosBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel1.add(puestosBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 150, 40));

        proveedoresBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        proveedoresBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        proveedoresBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                proveedoresBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                proveedoresBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                proveedoresBtnMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Proveedores");

        javax.swing.GroupLayout proveedoresBtnLayout = new javax.swing.GroupLayout(proveedoresBtn);
        proveedoresBtn.setLayout(proveedoresBtnLayout);
        proveedoresBtnLayout.setHorizontalGroup(
            proveedoresBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(proveedoresBtnLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        proveedoresBtnLayout.setVerticalGroup(
            proveedoresBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(proveedoresBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel1.add(proveedoresBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 150, 40));

        deptBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deptBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deptBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deptBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deptBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                deptBtnMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Departamentos");

        javax.swing.GroupLayout deptBtnLayout = new javax.swing.GroupLayout(deptBtn);
        deptBtn.setLayout(deptBtnLayout);
        deptBtnLayout.setHorizontalGroup(
            deptBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deptBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        deptBtnLayout.setVerticalGroup(
            deptBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deptBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel1.add(deptBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 150, 40));

        jPanel1.add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 70));

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        jPanel1.add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 880, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deptBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deptBtnMousePressed
        // TODO add your handling code here:
        x=1;
        SetColores color3 = new SetColores(proveedoresBtn);
        SetColores color4 = new SetColores(puestosBtn);
        SetColores2 color5 = new SetColores2(deptBtn);
        
        CrudDepartamento dep = new CrudDepartamento();
        dep.setSize(880, 410);
        dep.setLocation(0, 0);
        
        panel2.removeAll();
        panel2.add(dep,BorderLayout.CENTER);
        panel2.revalidate();
        panel2.repaint();
    }//GEN-LAST:event_deptBtnMousePressed

    private void puestosBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_puestosBtnMousePressed
        // TODO add your handling code here:
        x=2;
        SetColores color3 = new SetColores(proveedoresBtn);
        SetColores2 color4 = new SetColores2(puestosBtn);
        SetColores color5 = new SetColores(deptBtn);
        
        CrudPuesto puesto = new CrudPuesto();
        puesto.setSize(880, 410);
        puesto.setLocation(0, 0);
        
        panel2.removeAll();
        panel2.add(puesto,BorderLayout.CENTER);
        panel2.revalidate();
        panel2.repaint();
    }//GEN-LAST:event_puestosBtnMousePressed

    private void proveedoresBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proveedoresBtnMousePressed
        // TODO add your handling code here:
        x=3;
        SetColores2 color3 = new SetColores2(proveedoresBtn);
        SetColores color4 = new SetColores(puestosBtn);
        SetColores color5 = new SetColores(deptBtn);
        
        CrudProveedor prov = new CrudProveedor();
        prov.setSize(880, 410);
        prov.setLocation(0, 0);
        
        panel2.removeAll();
        panel2.add(prov,BorderLayout.CENTER);
        panel2.revalidate();
        panel2.repaint();
    }//GEN-LAST:event_proveedoresBtnMousePressed

    private void proveedoresBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proveedoresBtnMouseEntered
        // TODO add your handling code here:
        SetColores2 color = new SetColores2(proveedoresBtn);
    }//GEN-LAST:event_proveedoresBtnMouseEntered

    private void proveedoresBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proveedoresBtnMouseExited
        // TODO add your handling code here:
        if(x==3){
            
        }else{
            SetColores color = new SetColores(proveedoresBtn);
        }
    }//GEN-LAST:event_proveedoresBtnMouseExited

    private void puestosBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_puestosBtnMouseEntered
        // TODO add your handling code here:
        SetColores2 color = new SetColores2(puestosBtn);
    }//GEN-LAST:event_puestosBtnMouseEntered

    private void puestosBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_puestosBtnMouseExited
        // TODO add your handling code here:
        if(x==2){
            
        }else{
            SetColores color = new SetColores(puestosBtn);
        }
    }//GEN-LAST:event_puestosBtnMouseExited

    private void deptBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deptBtnMouseEntered
        // TODO add your handling code here:
        SetColores2 color = new SetColores2(deptBtn);
    }//GEN-LAST:event_deptBtnMouseEntered

    private void deptBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deptBtnMouseExited
        // TODO add your handling code here:
        if(x==1){
            
        }else{
            SetColores color = new SetColores(deptBtn);
        }
    }//GEN-LAST:event_deptBtnMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel deptBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel proveedoresBtn;
    private javax.swing.JPanel puestosBtn;
    // End of variables declaration//GEN-END:variables
}
