package crud;

import Metodos.SetColores;
import Metodos.SetColores2;
import Metodos.SetColores3;
import java.awt.BorderLayout;

public class InsertarEntradas extends javax.swing.JPanel {

    int x=0;
    public InsertarEntradas() {
        initComponents();
        SetColores3 color1 = new SetColores3(panel1);
        SetColores3 color2 = new SetColores3(panel2);
        SetColores color3 = new SetColores(facturasBtn);
        SetColores color = new SetColores(detallesBtn);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel1 = new javax.swing.JPanel();
        facturasBtn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        detallesBtn = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panel2 = new javax.swing.JPanel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setBackground(new java.awt.Color(102, 102, 102));
        panel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        facturasBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        facturasBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                facturasBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                facturasBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                facturasBtnMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Facturas entradas");

        javax.swing.GroupLayout facturasBtnLayout = new javax.swing.GroupLayout(facturasBtn);
        facturasBtn.setLayout(facturasBtnLayout);
        facturasBtnLayout.setHorizontalGroup(
            facturasBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(facturasBtnLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        facturasBtnLayout.setVerticalGroup(
            facturasBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, facturasBtnLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(14, 14, 14))
        );

        panel1.add(facturasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 170, 50));

        detallesBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        detallesBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                detallesBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                detallesBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                detallesBtnMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Crear detalle");

        javax.swing.GroupLayout detallesBtnLayout = new javax.swing.GroupLayout(detallesBtn);
        detallesBtn.setLayout(detallesBtnLayout);
        detallesBtnLayout.setHorizontalGroup(
            detallesBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detallesBtnLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        detallesBtnLayout.setVerticalGroup(
            detallesBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detallesBtnLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        panel1.add(detallesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 170, 50));

        jPanel1.add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 70));

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        jPanel1.add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 890, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void facturasBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facturasBtnMousePressed
        // TODO add your handling code here:
        x=1;
        SetColores color = new SetColores(detallesBtn);
        SetColores2 color1 = new SetColores2(facturasBtn);
        
        FacturasEntrada factura = new FacturasEntrada();
        factura.setSize(880, 410);
        factura.setLocation(0, 0);
        
        panel2.removeAll();
        panel2.add(factura,BorderLayout.CENTER);
        panel2.revalidate();
        panel2.repaint();
    }//GEN-LAST:event_facturasBtnMousePressed

    private void detallesBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detallesBtnMousePressed
        // TODO add your handling code here:
        x=2;
        SetColores2 color = new SetColores2(detallesBtn);
        SetColores color1 = new SetColores(facturasBtn);
        
        InsertarDetalleFactura insertar = new InsertarDetalleFactura();
        insertar.setSize(880, 410);
        insertar.setLocation(0, 0);
        
        panel2.removeAll();
        panel2.add(insertar,BorderLayout.CENTER);
        panel2.revalidate();
        panel2.repaint();
    }//GEN-LAST:event_detallesBtnMousePressed

    private void facturasBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facturasBtnMouseEntered
        // TODO add your handling code here:
        SetColores2 color = new SetColores2(facturasBtn);
    }//GEN-LAST:event_facturasBtnMouseEntered

    private void facturasBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facturasBtnMouseExited
        // TODO add your handling code here:
        if(x==1){
            
        }else{
            SetColores color = new SetColores(facturasBtn);
        }
    }//GEN-LAST:event_facturasBtnMouseExited

    private void detallesBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detallesBtnMouseEntered
        // TODO add your handling code here:
        SetColores2 color = new SetColores2(detallesBtn);
    }//GEN-LAST:event_detallesBtnMouseEntered

    private void detallesBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detallesBtnMouseExited
        // TODO add your handling code here:
        if(x==2){
            
        }else{
            SetColores color = new SetColores(detallesBtn);
        }
    }//GEN-LAST:event_detallesBtnMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel detallesBtn;
    private javax.swing.JPanel facturasBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    // End of variables declaration//GEN-END:variables
}
