/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carrito;

import Metodos.Fondos;
import Metodos.MetodosBD;
import Metodos.MetodosBD2;
import Metodos.MetodosJava;
import Metodos.Placeholder;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author roger
 */
public class CrearFactura extends javax.swing.JPanel {
    MetodosBD mbd=new MetodosBD();
    Fondos fondo2=new Fondos();
    MetodosBD2 mbd2 = new MetodosBD2();
    MetodosJava metodos3 = new MetodosJava();
    
    public CrearFactura() {
        initComponents();
        setColorPricipal(compraBtn);
        Placeholder caja = new Placeholder("Ingrese el nit del cliente",nitTxt);
        Placeholder caja2 = new Placeholder("Ingrese el nombre del cliente",nombreTxt);
        Placeholder caja3 = new Placeholder("Ingrese el nombre del cliente",apellidoTxt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        nitTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        nombreTxt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        apellidoTxt = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        compraBtn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nitTxt.setBorder(null);
        nitTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nitTxtActionPerformed(evt);
            }
        });
        add(nitTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 210, 30));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 210, -1));

        nombreTxt.setBorder(null);
        nombreTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTxtActionPerformed(evt);
            }
        });
        add(nombreTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 210, 30));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 210, 10));

        apellidoTxt.setBorder(null);
        apellidoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoTxtActionPerformed(evt);
            }
        });
        add(apellidoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 210, 30));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 210, 10));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 10, 230));

        compraBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                compraBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                compraBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                compraBtnMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Realizar compra");

        javax.swing.GroupLayout compraBtnLayout = new javax.swing.GroupLayout(compraBtn);
        compraBtn.setLayout(compraBtnLayout);
        compraBtnLayout.setHorizontalGroup(
            compraBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(compraBtnLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        compraBtnLayout.setVerticalGroup(
            compraBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, compraBtnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        add(compraBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 210, 30));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("NIT O CF");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 70, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Apellido");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 50, -1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Ingrese su información:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void nitTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nitTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nitTxtActionPerformed

    private void nombreTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTxtActionPerformed

    private void apellidoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoTxtActionPerformed

    private void compraBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_compraBtnMouseEntered
        // TODO add your handling code here:
        setColor(compraBtn);
    }//GEN-LAST:event_compraBtnMouseEntered

    private void compraBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_compraBtnMouseExited
        // TODO add your handling code here:
        setColorPricipal(compraBtn);
    }//GEN-LAST:event_compraBtnMouseExited

    private void compraBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_compraBtnMousePressed
        // TODO add your handling code here:
        mbd2.nuevaFactura(this.nitTxt.getText(), this.nombreTxt.getText(), this.apellidoTxt.getText());
        mbd2.nuevoDetalle();
        Factura2 f = new Factura2();
        Factura2.label3.setText(nombreTxt.getText()+" "+apellidoTxt.getText());
        Factura2.label4.setText(nitTxt.getText());
        Factura2.label7.setText(mbd.getObtenerusuario());
        Factura2.label1.setText(""+mbd.obtenerUltimaFactura(mbd.getObtenerusuario()));
        Factura2.label2.setText(mbd.obtenerFechaUltimaFactura(mbd.getObtenerusuario()));
        Factura2.label5.setText(mbd.obtenerSubtotalUltimaFactura(mbd.getObtenerusuario()));
        Factura2.label6.setText(mbd.obtenerTotalUltimaFactura(mbd.getObtenerusuario()));
        f.setVisible(true);
        metodos3.ncarrito.clear();
        this.setVisible(false);

    }//GEN-LAST:event_compraBtnMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidoTxt;
    private javax.swing.JPanel compraBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField nitTxt;
    private javax.swing.JTextField nombreTxt;
    // End of variables declaration//GEN-END:variables

    void setColorPricipal(JPanel panel){
        try{    
            mbd.obtenerColor();
            mbd.getModificarColor();
            if (mbd.getModificarColor().equals("azul")) {
                fondo2.azul(panel);
            } else if (mbd.getModificarColor().equals("negro")) {
                fondo2.oscuro(panel);
            } else if (mbd.getModificarColor().equals("negroBonito")) {
                fondo2.oscuroBonito(panel);

            } else if (mbd.getModificarColor().equals("azulBonito")) {
                fondo2.azulOscuro(panel);

            } else {
                
            }
        } catch (Exception e) {
                fondo2.azul(panel);
        }
    }

        void setColor(JPanel panel) {
        try {
            if (mbd.getModificarColor().equals("azul")) {
                fondo2.azulClaro(panel);
            } else if (mbd.getModificarColor().equals("negro")) {
                fondo2.oscuroClaro(panel);
            } else if (mbd.getModificarColor().equals("negroBonito")) {
                fondo2.oscuroBonitoClaro(panel);

            } else if (mbd.getModificarColor().equals("azulBonito")) {
                fondo2.azulOscuroClaro(panel);
            } else {
                JOptionPane.showMessageDialog(null, "Error con el color");
            }
        } catch (Exception e) {
            fondo2.azulClaro(panel);
        }
    }

}
