package proyectopersonal;

import Metodos.MetodosBD;
import crud.*;
import Metodos.MetodosBD2;
import Metodos.Placeholder;
import Metodos.SetColores;
import Metodos.SetColores2;
import Metodos.SetColores3;
import java.awt.BorderLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author roger
 */
public class CrearUsuario2 extends javax.swing.JPanel {

    MetodosBD2 metodos = new MetodosBD2();
    String ruta;
    MetodosBD metodos2 = new MetodosBD();
    private int num=0;
    
    public CrearUsuario2() {
        initComponents();
        
        SetColores3 color1 = new SetColores3(panel1);
        SetColores color2 = new SetColores(buscarImagenBtn);
        SetColores color = new SetColores(crearBtn);
        
        Placeholder caja1 = new Placeholder("Ingrese el usuario",usuarioTxt);
        Placeholder caja2 = new Placeholder("Ingrese el correo", correoTxt);
        Placeholder caja3 = new Placeholder("Ingrese la contraseña",contrasenaTxt);
        Placeholder caja4 = new Placeholder("Confirmar contraseña",confirmarContrasenaTxt);
        Placeholder caja5 = new Placeholder("Ingrese la pregunta de recuperación",preguntaTxt);
        Placeholder caja6 = new Placeholder("Ingrese la respuesta",respuestaTxt);
        
        SetColores3 ctxt1 = new SetColores3(usuarioTxt);
        SetColores3 ctxt2 = new SetColores3(correoTxt);
        SetColores3 ctxt3 = new SetColores3(contrasenaTxt);
        SetColores3 ctxt4 = new SetColores3(confirmarContrasenaTxt);
        SetColores3 ctxt5 = new SetColores3(preguntaTxt);
        SetColores3 ctxt6 = new SetColores3(respuestaTxt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        usuarioTxt = new javax.swing.JTextField();
        correoTxt = new javax.swing.JTextField();
        contrasenaTxt = new javax.swing.JTextField();
        confirmarContrasenaTxt = new javax.swing.JTextField();
        preguntaTxt = new javax.swing.JTextField();
        respuestaTxt = new javax.swing.JTextField();
        tipoTxt = new javax.swing.JComboBox<>();
        imagenLabel = new javax.swing.JLabel();
        buscarImagenBtn = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        rutaLabel = new javax.swing.JLabel();
        crearBtn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usuarioTxt.setBorder(null);
        usuarioTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioTxtActionPerformed(evt);
            }
        });
        panel1.add(usuarioTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 45, 190, 33));

        correoTxt.setBorder(null);
        panel1.add(correoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 136, 190, 33));

        contrasenaTxt.setBorder(null);
        panel1.add(contrasenaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 223, 190, 33));

        confirmarContrasenaTxt.setBorder(null);
        confirmarContrasenaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarContrasenaTxtActionPerformed(evt);
            }
        });
        panel1.add(confirmarContrasenaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 312, 190, 33));

        preguntaTxt.setBorder(null);
        panel1.add(preguntaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 45, 200, 33));

        respuestaTxt.setBorder(null);
        panel1.add(respuestaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 200, 33));

        tipoTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Empleado", "Administrador" }));
        panel1.add(tipoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 170, 30));

        imagenLabel.setBackground(new java.awt.Color(153, 153, 153));
        imagenLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel1.add(imagenLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, 160, 160));

        buscarImagenBtn.setBackground(new java.awt.Color(153, 153, 153));
        buscarImagenBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buscarImagenBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscarImagenBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buscarImagenBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buscarImagenBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buscarImagenBtnMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel2.setText("Subir foto");

        javax.swing.GroupLayout buscarImagenBtnLayout = new javax.swing.GroupLayout(buscarImagenBtn);
        buscarImagenBtn.setLayout(buscarImagenBtnLayout);
        buscarImagenBtnLayout.setHorizontalGroup(
            buscarImagenBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarImagenBtnLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        buscarImagenBtnLayout.setVerticalGroup(
            buscarImagenBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarImagenBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel1.add(buscarImagenBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 250, 140, 30));
        panel1.add(rutaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 210, 170, 20));

        crearBtn.setBackground(new java.awt.Color(153, 153, 153));
        crearBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        crearBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        crearBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                crearBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                crearBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                crearBtnMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Crear nuevo usuario");

        javax.swing.GroupLayout crearBtnLayout = new javax.swing.GroupLayout(crearBtn);
        crearBtn.setLayout(crearBtnLayout);
        crearBtnLayout.setHorizontalGroup(
            crearBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearBtnLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        crearBtnLayout.setVerticalGroup(
            crearBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        panel1.add(crearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 370, 250, 40));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 10, 400));
        panel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 200, 10));
        panel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 200, 10));
        panel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 200, 10));
        panel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 200, 10));
        panel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 200, 10));
        panel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 210, 10));

        jLabel3.setText("Usuario");
        panel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 150, -1));

        jLabel4.setText("Correo");
        panel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel5.setText("Contraseña");
        panel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel6.setText("Confirmar contraseña");
        panel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        jLabel7.setText("Pregunta secreta");
        panel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 90, 30));

        jLabel8.setText("Respuesta");
        panel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, -1, -1));

        jLabel9.setText("Tipo de usuario");
        panel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioTxtActionPerformed

    private void confirmarContrasenaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarContrasenaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmarContrasenaTxtActionPerformed

    private void crearBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearBtnMousePressed
        // TODO add your handling code here:
        //primero se valida que todos las cajas de textos estén llenas
        if(usuarioTxt.getText().length()>0 && correoTxt.getText().length()>0 && contrasenaTxt.getText().length()>0 || confirmarContrasenaTxt.getText().length()>0 &&
                preguntaTxt.getText().length()>0 && respuestaTxt.getText().length()>0){
            //si está llena entonces se hace la validación de contraseñas
            if(contrasenaTxt.getText().equals(confirmarContrasenaTxt.getText())){
                
                //Si la validación es correcta, entonces se valida si se inserta una imagen o no. 
                //Esto a través si el jlabel de la ruta está vacía.
                if(rutaLabel.getText().length()==0){
                       metodos.insertUsuarioSinFoto(usuarioTxt.getText(), correoTxt.getText(),  contrasenaTxt.getText(), 
                               preguntaTxt.getText(), respuestaTxt.getText(), 3);
                                irPanelSIguienteCliente();
                    
                    //al no estar vacía ya que al momento de elgir una imagen, se extrae la ruta en el label, en
                    //entonces hará lo siguiente
                }else{
                    //Se valida que tipo de usuario es, ya que en la BD Cliente =3, Empleado = 2, Administrador=3
                    //Esto en función de llaves foráneas
                       metodos.insertUsuario(usuarioTxt.getText(), correoTxt.getText(),  contrasenaTxt.getText(), 
                                preguntaTxt.getText(), respuestaTxt.getText(), 3, ruta);
                                irPanelSIguienteCliente();
                }
                //Validación incorrecta tira el siguiente mensaje:
            }else{
                JOptionPane.showMessageDialog(this, "Validación de contraseña incorrecta");
            }
            //Campos vacios tirará el siguiente mensaje
        }else{
            JOptionPane.showMessageDialog(this, "Debe de llenar todos los campos");
        }
    }//GEN-LAST:event_crearBtnMousePressed

    
    public void irPanelSIguienteCliente(){
        CrearCliente2 cliente = new CrearCliente2();
        cliente.setSize(880, 430);
        cliente.setLocation(0, 0);
        
        //tuve que hacer que el panel2 de la clase crudPersona fuera publica y static
        CrearUsuarioB.panel1.removeAll();
        CrearUsuarioB.panel1.add(cliente, BorderLayout.CENTER);
        CrearUsuarioB.panel1.revalidate();
        CrearUsuarioB.panel1.repaint();
        cliente.idTxt.setText(metodos2.obtenerUltimaIDCliente());
        cliente.idTxt.setEditable(false);
        cliente.usuarioTxt.setText(this.usuarioTxt.getText());//para asignar el usuario en la caja de texto del siguiente panel
                                                               //y así poder extraerlo en el método
        cliente.usuarioTxt.setEditable(false);//para que no se pueda editar la caja de texto
        
        metodos2.setObtenerusuario(usuarioTxt.getText());
        metodos2.setObtenertipo(3);
    }
    
    //método para buscar imagen
    private void buscarImagenBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarImagenBtnMousePressed
        // TODO add your handling code here:
        JFileChooser jfile = new JFileChooser();//manda a abrir un administrador de archivos
        int ap=jfile.showOpenDialog(this);
        if(ap == JFileChooser.APPROVE_OPTION){//si seleccionamos una imagene entonces hará lo siguiente:
            ruta = jfile.getSelectedFile().getAbsolutePath();//se obtiene la ruta de imagenen
            Image miimagen=new ImageIcon(ruta).getImage();
            ImageIcon miIcono = new ImageIcon(miimagen.getScaledInstance(imagenLabel.getWidth(), imagenLabel.getHeight(), 0));
            imagenLabel.setIcon(miIcono);
            rutaLabel.setText(ruta);
        }
    }//GEN-LAST:event_buscarImagenBtnMousePressed

    private void buscarImagenBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarImagenBtnMouseEntered
        // TODO add your handling code here:
        SetColores2 color = new SetColores2(buscarImagenBtn);
    }//GEN-LAST:event_buscarImagenBtnMouseEntered

    private void buscarImagenBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarImagenBtnMouseExited
        // TODO add your handling code here:
        SetColores color = new SetColores(buscarImagenBtn);
    }//GEN-LAST:event_buscarImagenBtnMouseExited

    private void crearBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearBtnMouseEntered
        // TODO add your handling code here:
        SetColores2 color = new SetColores2(crearBtn);
    }//GEN-LAST:event_crearBtnMouseEntered

    private void crearBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearBtnMouseExited
        // TODO add your handling code here:
        SetColores color = new SetColores(crearBtn);
    }//GEN-LAST:event_crearBtnMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buscarImagenBtn;
    private javax.swing.JTextField confirmarContrasenaTxt;
    private javax.swing.JTextField contrasenaTxt;
    private javax.swing.JTextField correoTxt;
    private javax.swing.JPanel crearBtn;
    private javax.swing.JLabel imagenLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JPanel panel1;
    private javax.swing.JTextField preguntaTxt;
    private javax.swing.JTextField respuestaTxt;
    private javax.swing.JLabel rutaLabel;
    public javax.swing.JComboBox<String> tipoTxt;
    private javax.swing.JTextField usuarioTxt;
    // End of variables declaration//GEN-END:variables
}
