package proyectopersonal;

import Metodos.Conexion;
import Metodos.FondoLabel;
import Metodos.Fondos;
import Metodos.MetodosBD;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


public class Ingreso extends javax.swing.JFrame {
    
    public CrearUsuarioB crear = new CrearUsuarioB();
    Fondos fondo1 = new Fondos("/imagenes/boton-x.png");
    Fondos fondo2 = new Fondos("/imagenes/login.png");
    Fondos fondo3 = new Fondos("/imagenes/minimizar.png");

    int xMouse,yMouse;
    
    FondoLabel esc=new FondoLabel();//clase para asignar imagenes a los labels
    
    public Ingreso() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        
        ocultarBtn.setVisible(false);
        esc.Escalar(verBtn, "/imagenes/ver.png");
        esc.Escalar(ocultarBtn, "/imagenes/ocultar.png");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        usuarioTxt = new javax.swing.JTextField();
        contrasenaTxt = new javax.swing.JPasswordField();
        jPanel2 = fondo2;
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ingresarPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        panelX = new javax.swing.JPanel();
        jPanel7 = fondo1;
        minimizarBtn = new javax.swing.JPanel();
        jPanel8 = fondo3;
        jLabel7 = new javax.swing.JLabel();
        verBtn = new javax.swing.JLabel();
        ocultarBtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(33, 45, 62));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(usuarioTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 202, 230, 36));
        jPanel1.add(contrasenaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 286, 230, 35));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 130, 130));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("USUARIO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 180, 76, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CONTRASEÑA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 256, -1, 24));

        ingresarPanel.setBackground(new java.awt.Color(0, 16, 40));
        ingresarPanel.setForeground(new java.awt.Color(255, 255, 255));
        ingresarPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingresarPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ingresarPanelMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("INGRESAR");

        javax.swing.GroupLayout ingresarPanelLayout = new javax.swing.GroupLayout(ingresarPanel);
        ingresarPanel.setLayout(ingresarPanelLayout);
        ingresarPanelLayout.setHorizontalGroup(
            ingresarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ingresarPanelLayout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(79, 79, 79))
        );
        ingresarPanelLayout.setVerticalGroup(
            ingresarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ingresarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(ingresarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 355, -1, -1));

        jPanel4.setBackground(new java.awt.Color(33, 45, 62));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel4MousePressed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Olvidó su contraseña?");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 327, -1, -1));

        jLabel5.setText("¿No tienes cuenta?");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 482, -1, -1));

        jPanel5.setBackground(new java.awt.Color(33, 45, 62));
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel5MousePressed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(102, 102, 102));
        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Regístrate");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel6))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 478, -1, -1));

        jPanel3.setBackground(new java.awt.Color(33, 45, 62));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelX.setBackground(new java.awt.Color(33, 45, 62));
        panelX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelXMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelXMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelXMousePressed(evt);
            }
        });
        panelX.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        panelX.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 10, 10));

        jPanel3.add(panelX, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 30, 30));

        minimizarBtn.setBackground(new java.awt.Color(33, 45, 62));
        minimizarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizarBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                minimizarBtnMousePressed(evt);
            }
        });
        minimizarBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        minimizarBtn.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 10, 10, 10));

        jPanel3.add(minimizarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 30, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("INICIAR SESIÓN");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 140, 140, -1));

        verBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        verBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                verBtnMousePressed(evt);
            }
        });
        jPanel1.add(verBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 30, 30));

        ocultarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ocultarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ocultarBtnMousePressed(evt);
            }
        });
        jPanel1.add(ocultarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Se asigna que cuando el mouse presione el panel, que haga la siguiente acción
    private void ingresarPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarPanelMousePressed
        // TODO add your handling code here:
        try{
            Conexion cn=new Conexion();
            MetodosBD metodo=new MetodosBD();
            cn.Conectar();
            //se asigna a estas variables lo de la caja de textos
            String us=this.usuarioTxt.getText();
            String con=contrasenaTxt.getText();
            
            //se asigna el sql
            String sql="select usuario, (CAST(aes_decrypt(contrasena,'AES')as char(20))) as contrasena,tipo "
                    + "from Usuarios where usuario='"+us+"'";
            cn.sentencia=cn.conexion.createStatement();
            cn.resultado=cn.sentencia.executeQuery(sql);
            
            //se obtiene los campos específicos media vez cumpla la condición del sql, se obtienen los datos
            //y se establecen en metodos set y get que están en otra clase(MetodoBD)
            while(cn.resultado.next()){
                metodo.setObtenerusuario(cn.resultado.getString("usuario"));
                metodo.setObtenercontrasena(cn.resultado.getString("contrasena"));
                metodo.setObtenertipo(cn.resultado.getInt("tipo"));
  
            }
            
            //como ya se estableció ahora se obtiene en el metodo get
            Menu menu = new Menu();
            if(metodo.getObtenerusuario().equals(us) && metodo.getObtenercontrasena().equals(con) &&
                    metodo.getObtenertipo()==1){
                    setVisible(false);
                    menu.setVisible(true);
                
            }else if(metodo.getObtenerusuario().equals(us) && metodo.getObtenercontrasena().equals(con) &&
                    metodo.getObtenertipo()==2){
                    JOptionPane.showMessageDialog(rootPane, "Bienvenido tabajador");
                    setVisible(false);
                    menu.setVisible(true);
                
            }else if(metodo.getObtenerusuario().equals(us) && metodo.getObtenercontrasena().equals(con) &&
                    metodo.getObtenertipo()==3){
                    JOptionPane.showMessageDialog(rootPane, "Bienvenido cliente");
                    setVisible(false);
                    menu.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Contraseña o usuario incorrecta: ");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Usuario o contraseña incorrecta.");
        }
    }//GEN-LAST:event_ingresarPanelMousePressed

    private void panelXMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelXMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_panelXMousePressed

    private void panelXMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelXMouseEntered
        // TODO add your handling code here:
        this.setColor(panelX);
    }//GEN-LAST:event_panelXMouseEntered

    private void panelXMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelXMouseExited
        // TODO add your handling code here:
        this.resetColor(panelX);
    }//GEN-LAST:event_panelXMouseExited

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        // TODO add your handling code here:
        //para mover el panel de arriba con el mouse
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    private void verBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verBtnMousePressed
        // TODO add your handling code here:
        verBtn.setVisible(false);
        ocultarBtn.setVisible(true);
        contrasenaTxt.setEchoChar((char)0);
    }//GEN-LAST:event_verBtnMousePressed

    private void ocultarBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ocultarBtnMousePressed
        // TODO add your handling code here:
        ocultarBtn.setVisible(false);//oculta la contrasena
        verBtn.setVisible(true);
        contrasenaTxt.setEchoChar('*');
    }//GEN-LAST:event_ocultarBtnMousePressed

    private void jPanel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MousePressed
        // TODO add your handling code here:
        setVisible(false);
        RecuperacionContrasena recuperacion = new RecuperacionContrasena();
        recuperacion.setVisible(true);
    }//GEN-LAST:event_jPanel4MousePressed

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseEntered
        // TODO add your handling code here:
        jLabel4.setForeground(Color.gray);
    }//GEN-LAST:event_jPanel4MouseEntered

    private void jPanel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseExited
        // TODO add your handling code here:
        jLabel4.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_jPanel4MouseExited

    private void jPanel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseEntered
        // TODO add your handling code here:
        jLabel6.setForeground(Color.gray);
    }//GEN-LAST:event_jPanel5MouseEntered

    private void jPanel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseExited
        // TODO add your handling code here:
        jLabel6.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_jPanel5MouseExited

    private void jPanel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MousePressed
        // TODO add your handling code here:
        setVisible(false);
        CrearUsuarioB crear = new CrearUsuarioB();
        crear.setVisible(true);
    }//GEN-LAST:event_jPanel5MousePressed

    private void minimizarBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarBtnMousePressed
        // TODO add your handling code here:
        setExtendedState(1);
    }//GEN-LAST:event_minimizarBtnMousePressed

    private void minimizarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarBtnMouseExited
        // TODO add your handling code here:
        minimizarBtn.setBackground(new Color(33,45,62));
    }//GEN-LAST:event_minimizarBtnMouseExited

    private void minimizarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarBtnMouseEntered
        // TODO add your handling code here:
        minimizarBtn.setBackground(new Color(40,48,68));
    }//GEN-LAST:event_minimizarBtnMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField contrasenaTxt;
    private javax.swing.JPanel ingresarPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel minimizarBtn;
    private javax.swing.JLabel ocultarBtn;
    private javax.swing.JPanel panelX;
    private javax.swing.JTextField usuarioTxt;
    private javax.swing.JLabel verBtn;
    // End of variables declaration//GEN-END:variables

    void setColor(JPanel panel) {
        panel.setBackground(new Color(255, 0, 2));

    }
    
    void resetColor(JPanel panel){
        panel.setBackground(new Color(33,45,62));
    }
    
}


