
package proyectopersonal;

import java.awt.BorderLayout;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import Metodos.Fondos;
import Metodos.MetodosBD;
import Metodos.Conexion;
import Metodos.FondoLabel;
import Metodos.MetodosJava;
import Metodos.SetColores;
import Metodos.SetColores2;
import Metodos.SetColores3;
import carrito.Carrito;
import crud.crudPrincipal;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.InputStream;
import javax.imageio.ImageIO;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import perfil.Perfil;

/**
 *
 * @author roger
 */
public class Menu extends javax.swing.JFrame {
    
    //establecer imagenes de los botones
    Fondos fondo1=new Fondos("/imagenes/Producto.png");
    Fondos fondo2=new Fondos();
    Fondos fondo3=new Fondos("/imagenes/correo-de-contacto.png");
    Fondos fondo4=new Fondos("/imagenes/administrar.png");
    Fondos fondo5=new Fondos("/imagenes/carrito-de-compras.png");
    Fondos fondo6=new Fondos("/imagenes/cerrar-sesion.png");
    Fondos fondo7=new Fondos("/imagenes/boton-x.png");
    Fondos fondo8=new Fondos("/imagenes/minimizar.png");
    
    CambioFondo cambiof=new CambioFondo();
    MetodosBD mbd=new MetodosBD();
    Conexion cn=new Conexion();
    MetodosJava metodos3 = new MetodosJava();
    
    int xMouse,yMouse;//variable dedicadas para poder mover la ventana
    
    private int x=0;//variable dedicada para establecer cada vez que se presiona un botó y así cambiar color
    public Menu() {
        initComponents();
        mbd.obtenerColor();
        
        setResizable(false);
        setTitle("login");
        setLocationRelativeTo(null);
        
        usuarioLabel.setText(mbd.getObtenerusuario());
        
        SetColores color1 = new SetColores(panel1);//establecer colores
        SetColores3 color2 = new SetColores3(panel2);
        SetColores color3 = new SetColores(panel3);
        SetColores color4 = new SetColores(verProductoBtn);
        SetColores color5 = new SetColores(Panel11);
        SetColores color6 = new SetColores(carritoBtn);
        SetColores color7 = new SetColores(contactoBtn);
        SetColores color8 = new SetColores(administracionBtn);
        SetColores color9 = new SetColores(editarBtn);
        SetColores color10 = new SetColores(salirBtn);
        SetColores color11 = new SetColores(opcionesBtn);
        SetColores color12 = new SetColores(cerrarBtn);
        SetColores color13 = new SetColores(minimizarBtn);
        
        verFot();
        roles();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        verProductoBtn = new javax.swing.JPanel();
        Panel11 = fondo1;
        jLabel2 = new javax.swing.JLabel();
        carritoBtn = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Panel12 = fondo5;
        contactoBtn = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Panel13 = fondo3;
        usuarioLabel = new javax.swing.JLabel();
        editarBtn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        administracionBtn = new javax.swing.JPanel();
        Panel14 = fondo4;
        jLabel6 = new javax.swing.JLabel();
        salirBtn = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Panel15 = fondo6;
        imagenLabel = new javax.swing.JLabel();
        panel2 = new javax.swing.JPanel();
        panel3 = new javax.swing.JPanel();
        opcionesBtn = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cerrarBtn = new javax.swing.JPanel();
        xBtn = fondo7;
        minimizarBtn = new javax.swing.JPanel();
        jPanel2 = fondo8;

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setBackground(new java.awt.Color(51, 61, 131));
        panel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        verProductoBtn.setBackground(new java.awt.Color(51, 61, 131));
        verProductoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        verProductoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verProductoBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verProductoBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                verProductoBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                verProductoBtnMousePressed(evt);
            }
        });
        verProductoBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout Panel11Layout = new javax.swing.GroupLayout(Panel11);
        Panel11.setLayout(Panel11Layout);
        Panel11Layout.setHorizontalGroup(
            Panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );
        Panel11Layout.setVerticalGroup(
            Panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        verProductoBtn.add(Panel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 38));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ver productos");
        verProductoBtn.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 6, 129, 38));

        panel1.add(verProductoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 320, 50));

        carritoBtn.setBackground(new java.awt.Color(51, 61, 131));
        carritoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        carritoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                carritoBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                carritoBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                carritoBtnMousePressed(evt);
            }
        });
        carritoBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ver carrito de compra");
        carritoBtn.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 6, 169, 38));

        javax.swing.GroupLayout Panel12Layout = new javax.swing.GroupLayout(Panel12);
        Panel12.setLayout(Panel12Layout);
        Panel12Layout.setHorizontalGroup(
            Panel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );
        Panel12Layout.setVerticalGroup(
            Panel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        carritoBtn.add(Panel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        panel1.add(carritoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 320, 50));

        contactoBtn.setBackground(new java.awt.Color(51, 61, 131));
        contactoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        contactoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                contactoBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                contactoBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                contactoBtnMousePressed(evt);
            }
        });
        contactoBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contactar a la compañía");
        contactoBtn.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 6, 189, 38));

        javax.swing.GroupLayout Panel13Layout = new javax.swing.GroupLayout(Panel13);
        Panel13.setLayout(Panel13Layout);
        Panel13Layout.setHorizontalGroup(
            Panel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );
        Panel13Layout.setVerticalGroup(
            Panel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        contactoBtn.add(Panel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 38));

        panel1.add(contactoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 320, 50));

        usuarioLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        usuarioLabel.setForeground(new java.awt.Color(255, 255, 255));
        usuarioLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usuarioLabel.setText("jLabel5");
        usuarioLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panel1.add(usuarioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 140, -1));

        editarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editarBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editarBtnMousePressed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Editar");

        javax.swing.GroupLayout editarBtnLayout = new javax.swing.GroupLayout(editarBtn);
        editarBtn.setLayout(editarBtnLayout);
        editarBtnLayout.setHorizontalGroup(
            editarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editarBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        editarBtnLayout.setVerticalGroup(
            editarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editarBtnLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        panel1.add(editarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, 20));

        administracionBtn.setBackground(new java.awt.Color(51, 61, 131));
        administracionBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        administracionBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                administracionBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                administracionBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                administracionBtnMousePressed(evt);
            }
        });
        administracionBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout Panel14Layout = new javax.swing.GroupLayout(Panel14);
        Panel14.setLayout(Panel14Layout);
        Panel14Layout.setHorizontalGroup(
            Panel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );
        Panel14Layout.setVerticalGroup(
            Panel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        administracionBtn.add(Panel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 38));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Administracion BD");
        administracionBtn.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 6, 189, 38));

        panel1.add(administracionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 320, 50));

        salirBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salirBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salirBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salirBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                salirBtnMousePressed(evt);
            }
        });
        salirBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cerrar sesión");
        salirBtn.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 8, 190, 40));

        javax.swing.GroupLayout Panel15Layout = new javax.swing.GroupLayout(Panel15);
        Panel15.setLayout(Panel15Layout);
        Panel15Layout.setHorizontalGroup(
            Panel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );
        Panel15Layout.setVerticalGroup(
            Panel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        salirBtn.add(Panel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 38));

        panel1.add(salirBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 320, 50));
        panel1.add(imagenLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 130, 150));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 23, 320, 610));

        panel2.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        getContentPane().add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 23, -1, 610));

        panel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panel3MouseDragged(evt);
            }
        });
        panel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel3MousePressed(evt);
            }
        });
        panel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        opcionesBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                opcionesBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                opcionesBtnMouseExited(evt);
            }
        });
        opcionesBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Opciones");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });
        opcionesBtn.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 80, 23));

        panel3.add(opcionesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 90, 23));

        cerrarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cerrarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cerrarBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cerrarBtnMousePressed(evt);
            }
        });
        cerrarBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout xBtnLayout = new javax.swing.GroupLayout(xBtn);
        xBtn.setLayout(xBtnLayout);
        xBtnLayout.setHorizontalGroup(
            xBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        xBtnLayout.setVerticalGroup(
            xBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        cerrarBtn.add(xBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 7, 10, 10));

        panel3.add(cerrarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 0, 30, 23));

        minimizarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizarBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                minimizarBtnMousePressed(evt);
            }
        });
        minimizarBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );

        minimizarBtn.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 6, -1, -1));

        panel3.add(minimizarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1139, 0, 30, 23));

        getContentPane().add(panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verProductoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verProductoBtnMouseClicked

    }//GEN-LAST:event_verProductoBtnMouseClicked

    private void verProductoBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verProductoBtnMousePressed
        // TODO add your handling code here:
        
        //se manda a llamar al metodo de cambiar el colo, esto es para cuando se presione el panel
        x=1;
        SetColores2 color4 = new SetColores2(verProductoBtn);
        SetColores2 color5 = new SetColores2(Panel11);
        SetColores color6 = new SetColores(carritoBtn);
        SetColores color7 = new SetColores(contactoBtn);
        SetColores color8 = new SetColores(administracionBtn);
        SetColores color9 = new SetColores(editarBtn);

        //esto es para cuando se preseione el panel, made a traer al Jframe y lo ponga en el panel asignado
        VerProductos vp=new VerProductos();
        vp.setSize(880,610);
        vp.setLocation(0,0);
        
        panel2.removeAll();
        panel2.add(vp,BorderLayout.CENTER);
        panel2.revalidate();
        panel2.repaint();
        
    }//GEN-LAST:event_verProductoBtnMousePressed

    //este es para cuando el mouse pasa encima del panel,cambie de color
    private void verProductoBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verProductoBtnMouseEntered
        // TODO add your handling code here:
        SetColores2 color = new SetColores2(verProductoBtn);
    }//GEN-LAST:event_verProductoBtnMouseEntered

    //este para cuando el mouse ya no esté en el panel
    private void verProductoBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verProductoBtnMouseExited
        // TODO add your handling code here:
        if(x==1){
            //no se hace nada porque el botoón está seleccionado y no quiero que se cambie de color
        }else{
            SetColores color4 = new SetColores(verProductoBtn);
        }
    }//GEN-LAST:event_verProductoBtnMouseExited

    private void carritoBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carritoBtnMousePressed
        // TODO add your handling code here:
        x=2;
        SetColores2 color4 = new SetColores2(carritoBtn);
        SetColores color5 = new SetColores(Panel11);
        SetColores color6 = new SetColores(verProductoBtn);
        SetColores color7 = new SetColores(contactoBtn);
        SetColores color8 = new SetColores(administracionBtn);
        SetColores color9 = new SetColores(editarBtn);
        
        Carrito carrito = new Carrito();
        carrito.setSize(880,610);
        carrito.setLocation(0,0);
        
        panel2.removeAll();
        panel2.add(carrito,BorderLayout.CENTER);
        panel2.revalidate();
        panel2.repaint();
        
    }//GEN-LAST:event_carritoBtnMousePressed

    private void carritoBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carritoBtnMouseEntered
        // TODO add your handling code here:
        SetColores2 color = new SetColores2(carritoBtn);
    }//GEN-LAST:event_carritoBtnMouseEntered

    private void carritoBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carritoBtnMouseExited
        // TODO add your handling code here:
        if(x==2){
            
        }else{
            SetColores color = new SetColores(carritoBtn);
        }
    }//GEN-LAST:event_carritoBtnMouseExited

    private void contactoBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactoBtnMousePressed
        // TODO add your handling code here:
        x=3;
        SetColores2 color4 = new SetColores2(contactoBtn);
        SetColores color5 = new SetColores(Panel11);
        SetColores color6 = new SetColores(verProductoBtn);
        SetColores color7 = new SetColores(carritoBtn);
        SetColores color8 = new SetColores(administracionBtn);
        SetColores color9 = new SetColores(editarBtn);
        
        AcercaDeCompania compania = new AcercaDeCompania();
        compania.setSize(880,610);
        compania.setLocation(0, 0);
        
        panel2.removeAll();
        panel2.add(compania,BorderLayout.CENTER);
        panel2.revalidate();
        panel2.repaint();
    }//GEN-LAST:event_contactoBtnMousePressed

    private void contactoBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactoBtnMouseEntered
        // TODO add your handling code here:
        SetColores2 color4 = new SetColores2(contactoBtn);
    }//GEN-LAST:event_contactoBtnMouseEntered

    private void contactoBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactoBtnMouseExited
        // TODO add your handling code here:
        if(x==3){
            
        }else{
            SetColores color4 = new SetColores(contactoBtn);
        }
    }//GEN-LAST:event_contactoBtnMouseExited

    private void editarBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarBtnMousePressed
        // TODO add your handling code here:
        x=4;
        SetColores2 color4 = new SetColores2(editarBtn);
        SetColores color5 = new SetColores(Panel11);
        SetColores color6 = new SetColores(verProductoBtn);
        SetColores color7 = new SetColores(carritoBtn);
        SetColores color8 = new SetColores(administracionBtn);
        SetColores color9 = new SetColores(contactoBtn);
        
        Perfil perfil = new Perfil();
        perfil.setSize(880,610);
        perfil.setLocation(0,0);
        panel2.removeAll();
        panel2.add(perfil,BorderLayout.CENTER);
        panel2.revalidate();
        panel2.repaint();
    }//GEN-LAST:event_editarBtnMousePressed

    private void editarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarBtnMouseEntered
        // TODO add your handling code here:
        SetColores2 color4 = new SetColores2(editarBtn);
    }//GEN-LAST:event_editarBtnMouseEntered

    private void editarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarBtnMouseExited
        // TODO add your handling code here:
        if(x==4){
            
        }else{
            SetColores color = new SetColores(editarBtn);
        }
    }//GEN-LAST:event_editarBtnMouseExited

    private void administracionBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_administracionBtnMouseEntered
        // TODO add your handling code here:
         SetColores2 color4 = new SetColores2(administracionBtn);
    }//GEN-LAST:event_administracionBtnMouseEntered

    private void administracionBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_administracionBtnMouseExited
        // TODO add your handling code here:
        if(x==5){
            
        }else{
             SetColores color = new SetColores(administracionBtn);
        }
    }//GEN-LAST:event_administracionBtnMouseExited

    private void administracionBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_administracionBtnMousePressed
        // TODO add your handling code here:
        x=5;
        SetColores2 color4 = new SetColores2(administracionBtn);
        SetColores color5 = new SetColores(Panel11);
        SetColores color6 = new SetColores(verProductoBtn);
        SetColores color7 = new SetColores(carritoBtn);
        SetColores color8 = new SetColores(editarBtn);
        SetColores color9 = new SetColores(contactoBtn);
        
        crudPrincipal crud=new crudPrincipal();
        crud.setSize(880,610);
        crud.setLocation(0,0);
        panel2.removeAll();
        panel2.add(crud,BorderLayout.CENTER);
        panel2.revalidate();
        panel2.repaint();
    }//GEN-LAST:event_administracionBtnMousePressed

    private void salirBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirBtnMousePressed
        // TODO add your handling code here:
        setVisible(false);
        metodos3.ncarrito.clear();
        metodos3.cantidad.clear();
        Ingreso ingreso=new Ingreso();
        ingreso.setVisible(true);
        
        mbd.setObtenerusuario("");
        mbd.setObtenertipo(0);
       
    }//GEN-LAST:event_salirBtnMousePressed

    private void salirBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirBtnMouseEntered
        // TODO add your handling code here:
        SetColores2 color1 = new SetColores2(salirBtn);
    }//GEN-LAST:event_salirBtnMouseEntered

    private void salirBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirBtnMouseExited
        // TODO add your handling code here:
        SetColores color = new SetColores(salirBtn);
    }//GEN-LAST:event_salirBtnMouseExited

    private void opcionesBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcionesBtnMouseEntered
        // TODO add your handling code here:
        SetColores2 color10 = new SetColores2(opcionesBtn);
    }//GEN-LAST:event_opcionesBtnMouseEntered

    private void opcionesBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcionesBtnMouseExited
        // TODO add your handling code here:
        SetColores color10 = new SetColores(opcionesBtn);
    }//GEN-LAST:event_opcionesBtnMouseExited

    private void cerrarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarBtnMouseEntered
        // TODO add your handling code here:
        cerrarBtn.setBackground(new Color(255,0,2));
    }//GEN-LAST:event_cerrarBtnMouseEntered

    private void cerrarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarBtnMouseExited
        // TODO add your handling code here:
        SetColores color10 = new SetColores(cerrarBtn);
    }//GEN-LAST:event_cerrarBtnMouseExited

    private void cerrarBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarBtnMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_cerrarBtnMousePressed

    private void panel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel3MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_panel3MouseDragged

    private void panel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel3MousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_panel3MousePressed

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        // TODO add your handling code here:
        CambioFondo cambio = new CambioFondo();
        setVisible(false);
        cambio.setVisible(true);
        
    }//GEN-LAST:event_jLabel7MousePressed

    private void minimizarBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarBtnMousePressed
        // TODO add your handling code here:
        setExtendedState(1);
    }//GEN-LAST:event_minimizarBtnMousePressed

    private void minimizarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarBtnMouseExited
        // TODO add your handling code here:
        SetColores color = new SetColores(minimizarBtn);
    }//GEN-LAST:event_minimizarBtnMouseExited

    private void minimizarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarBtnMouseEntered
        // TODO add your handling code here:
        SetColores2 color1 = new SetColores2(minimizarBtn);
    }//GEN-LAST:event_minimizarBtnMouseEntered

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        // TODO add your handling code here:
        SetColores2 color1 = new SetColores2(opcionesBtn);
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        // TODO add your handling code here:
        SetColores color1 = new SetColores(opcionesBtn);
    }//GEN-LAST:event_jLabel7MouseExited

    //ver foto en el label
    public void verFot(){
        Conexion cn=new Conexion();
        cn.Conectar();
        
        String sql="select foto from usuarios where usuario='"+mbd.getObtenerusuario()+"'";
        ImageIcon foto;
        InputStream is;
        
        //en el caso que exista foto, se hará lo siguiente
        try{
            cn.sentencia=cn.conexion.createStatement();
            cn.resultado=cn.sentencia.executeQuery(sql);
            while(cn.resultado.next()){
                is=cn.resultado.getBinaryStream(1);
                BufferedImage bi = ImageIO.read(is);
                foto = new ImageIcon(bi);
                Image img = foto.getImage();
                Image newimg = img.getScaledInstance(130, 150, java.awt.Image.SCALE_SMOOTH);
                ImageIcon  newicon = new ImageIcon(newimg);
                imagenLabel.setIcon(newicon);    
            }
            
            //en el caso de que no haya fotos, aparecerá la foto establecida
        }catch(Exception e){
           FondoLabel esc=new FondoLabel();
           esc.Escalar(imagenLabel, "/imagenes/usuario.png");
        }
    }
    
    public void roles(){//unicamente roles de usuario
        if(mbd.getObtenertipo()==3){
            administracionBtn.setVisible(false);
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel11;
    private javax.swing.JPanel Panel12;
    private javax.swing.JPanel Panel13;
    private javax.swing.JPanel Panel14;
    private javax.swing.JPanel Panel15;
    private javax.swing.JPanel administracionBtn;
    private javax.swing.JPanel carritoBtn;
    private javax.swing.JPanel cerrarBtn;
    private javax.swing.JPanel contactoBtn;
    private javax.swing.JPanel editarBtn;
    private javax.swing.JLabel imagenLabel;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel minimizarBtn;
    private javax.swing.JPanel opcionesBtn;
    public static javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JPanel salirBtn;
    private javax.swing.JLabel usuarioLabel;
    public static javax.swing.JPanel verProductoBtn;
    private javax.swing.JPanel xBtn;
    // End of variables declaration//GEN-END:variables

}


