package proyectopersonal;

import Metodos.Fondos;
import Metodos.MetodosBD2;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

public class RecuperacionContrasena extends javax.swing.JFrame {

        Fondos fondo1 = new Fondos("/imagenes/boton-x.png");
        MetodosBD2 metodos = new MetodosBD2();
        int xMouse,yMouse;
        
    public RecuperacionContrasena() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        
        nuevaContra.setVisible(false);
        confirmacionTxt.setVisible(false);
        cambiarBtn.setVisible(false);
        preguntaTxt.setVisible(false);
        respuestaTxt.setVisible(false);
        verificarBtn.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        respuestaTxt = new javax.swing.JTextField();
        usuarioTxt = new javax.swing.JTextField();
        confirmacionTxt = new javax.swing.JTextField();
        nuevaContra = new javax.swing.JTextField();
        cambiarBtn = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cambiarBtn1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        verificarBtn = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        preguntaTxt = new javax.swing.JLabel();
        panel2 = new javax.swing.JPanel();
        panel3 = new javax.swing.JPanel();
        jPanel4 = fondo1;
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        cancelarBtn = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panel1.setBackground(new java.awt.Color(255, 255, 255));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panel1.add(respuestaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 227, 34));

        usuarioTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioTxtActionPerformed(evt);
            }
        });
        panel1.add(usuarioTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 227, 34));
        panel1.add(confirmacionTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 227, 34));
        panel1.add(nuevaContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 227, 34));

        cambiarBtn.setBackground(new java.awt.Color(0, 16, 40));
        cambiarBtn.setForeground(new java.awt.Color(255, 255, 255));
        cambiarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cambiarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cambiarBtnMousePressed(evt);
            }
        });
        cambiarBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cambiar");
        cambiarBtn.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        cambiarBtn1.setBackground(new java.awt.Color(0, 16, 40));
        cambiarBtn1.setForeground(new java.awt.Color(255, 255, 255));
        cambiarBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cambiarBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cambiarBtn1MousePressed(evt);
            }
        });
        cambiarBtn1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Cambiar");
        cambiarBtn1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        cambiarBtn.add(cambiarBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 180, 50));

        panel1.add(cambiarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 180, 50));

        verificarBtn.setBackground(new java.awt.Color(0, 16, 40));
        verificarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        verificarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                verificarBtnMousePressed(evt);
            }
        });
        verificarBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Verificar");
        verificarBtn.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 6, -1, 38));

        panel1.add(verificarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 180, 50));
        panel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 480, -1));

        preguntaTxt.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        preguntaTxt.setForeground(new java.awt.Color(0, 0, 0));
        panel1.add(preguntaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 430, 30));

        panel2.setBackground(new java.awt.Color(33, 45, 62));
        panel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panel2MouseDragged(evt);
            }
        });
        panel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel2MousePressed(evt);
            }
        });
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel3.setBackground(new java.awt.Color(33, 45, 62));
        panel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel3MousePressed(evt);
            }
        });
        panel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        panel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        panel2.add(panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 30, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Recuperación de contraseña");
        panel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 30));

        panel1.add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 30));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuario");
        panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 46, 70, 20));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Respuesta");
        panel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));
        panel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 173, 430, 10));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nueva contraseña");
        panel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Confirmación");
        panel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 90, -1));
        panel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 500, -1));

        jLabel8.setText("Pregunta");
        panel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 50, -1));

        cancelarBtn.setBackground(new java.awt.Color(0, 16, 40));
        cancelarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cancelarBtnMousePressed(evt);
            }
        });
        cancelarBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Cancelar");
        cancelarBtn.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 6, -1, 38));

        panel1.add(cancelarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 180, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verificarBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verificarBtnMousePressed
        // TODO add your handling code here:
        //verifica la respuesta y vayan apareciendo nuevos botones si es correcto
        metodos.verificarRespuesta(usuarioTxt.getText(), respuestaTxt.getText(), nuevaContra, confirmacionTxt,respuestaTxt,verificarBtn,cambiarBtn);
        
    }//GEN-LAST:event_verificarBtnMousePressed

    private void usuarioTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioTxtActionPerformed
        // TODO add your handling code here:
        preguntaTxt.setText("");
        respuestaTxt.setVisible(false);
        verificarBtn.setVisible(false);
        metodos.buscarUsuario(usuarioTxt.getText(), preguntaTxt, respuestaTxt, verificarBtn);
        //se verifica si el usuario existe o no
        if(preguntaTxt.getText().equals("")){
            preguntaTxt.setVisible(true);
            preguntaTxt.setText("Usuario inválido");
        }else{
            usuarioTxt.setEditable(false);
            evt.setSource((char) KeyEvent.VK_CLEAR);
            respuestaTxt.requestFocus();
        }
    }//GEN-LAST:event_usuarioTxtActionPerformed

    //cambio de contrase4ña
    private void cambiarBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cambiarBtnMousePressed
        // TODO add your handling code here:
        if(nuevaContra.getText().equals(confirmacionTxt.getText())){
            metodos.cambiarContrasena(usuarioTxt.getText(), nuevaContra.getText());
            setVisible(false);
            Ingreso ingreso = new Ingreso();
            ingreso.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Error: asegurese de escribir correctamente en la confirmación");
        }
    }//GEN-LAST:event_cambiarBtnMousePressed

    private void panel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel3MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_panel3MousePressed

    private void panel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel3MouseEntered
        // TODO add your handling code here:
        panel3.setBackground(new Color(255,0,2));
    }//GEN-LAST:event_panel3MouseEntered

    private void panel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel3MouseExited
        // TODO add your handling code here:
        panel3.setBackground(new Color(33,45,62));
    }//GEN-LAST:event_panel3MouseExited

    private void panel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel2MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_panel2MouseDragged

    private void panel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel2MousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_panel2MousePressed

    private void cambiarBtn1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cambiarBtn1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cambiarBtn1MousePressed

    private void cancelarBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarBtnMousePressed
        // TODO add your handling code here:
        setVisible(false);
        Ingreso ingreso = new Ingreso();
        ingreso.setVisible(true);
    }//GEN-LAST:event_cancelarBtnMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecuperacionContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecuperacionContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecuperacionContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecuperacionContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecuperacionContrasena().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cambiarBtn;
    private javax.swing.JPanel cambiarBtn1;
    private javax.swing.JPanel cancelarBtn;
    private javax.swing.JTextField confirmacionTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField nuevaContra;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JLabel preguntaTxt;
    private javax.swing.JTextField respuestaTxt;
    private javax.swing.JTextField usuarioTxt;
    private javax.swing.JPanel verificarBtn;
    // End of variables declaration//GEN-END:variables
}
