/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perfil;

import Metodos.MetodosBD;
import Metodos.MetodosBD2;
import Metodos.Placeholder;
import Metodos.SetColores;
import Metodos.SetColores2;
import Metodos.SetColores3;
import javax.swing.JOptionPane;

/**
 *
 * @author roger
 */
public class CambiarContra extends javax.swing.JDialog {

    /**
     * Creates new form CmabiarContra
     */
    public CambiarContra(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        setLocationRelativeTo(null);
        
        SetColores3 color1 = new SetColores3(panel1);
        SetColores color2 = new SetColores(modificarBtn);
        SetColores color3 = new SetColores(cancelarBtn);
        
        SetColores3 color5 = new SetColores3(newContraTx);
        SetColores3 color6 = new SetColores3(confirmacionTxt);
        

        Placeholder caja2 = new Placeholder("Ingrese la nueva contraseña",newContraTx);
        Placeholder caja3 = new Placeholder("Confirmación de nueva contraseña",confirmacionTxt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        cancelarBtn = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        modificarBtn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        newContraTx = new javax.swing.JPasswordField();
        confirmacionTxt = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        panel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cancelarBtn.setBackground(new java.awt.Color(102, 102, 102));
        cancelarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelarBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cancelarBtnMousePressed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cancelar");

        javax.swing.GroupLayout cancelarBtnLayout = new javax.swing.GroupLayout(cancelarBtn);
        cancelarBtn.setLayout(cancelarBtnLayout);
        cancelarBtnLayout.setHorizontalGroup(
            cancelarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cancelarBtnLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        cancelarBtnLayout.setVerticalGroup(
            cancelarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cancelarBtnLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        panel1.add(cancelarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, -1, -1));

        modificarBtn.setBackground(new java.awt.Color(102, 102, 102));
        modificarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                modificarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                modificarBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                modificarBtnMousePressed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Modificar");

        javax.swing.GroupLayout modificarBtnLayout = new javax.swing.GroupLayout(modificarBtn);
        modificarBtn.setLayout(modificarBtnLayout);
        modificarBtnLayout.setHorizontalGroup(
            modificarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarBtnLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        modificarBtnLayout.setVerticalGroup(
            modificarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modificarBtnLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        panel1.add(modificarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));
        panel1.add(newContraTx, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 230, 40));
        panel1.add(confirmacionTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 230, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarBtnMousePressed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_cancelarBtnMousePressed

    private void modificarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarBtnMouseEntered
        // TODO add your handling code here:
        SetColores2 color = new SetColores2(modificarBtn);
    }//GEN-LAST:event_modificarBtnMouseEntered

    private void modificarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarBtnMouseExited
        // TODO add your handling code here:
        SetColores color = new SetColores(modificarBtn);
    }//GEN-LAST:event_modificarBtnMouseExited

    private void cancelarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarBtnMouseEntered
        // TODO add your handling code here:
        SetColores2 color = new SetColores2(cancelarBtn);
    }//GEN-LAST:event_cancelarBtnMouseEntered

    private void cancelarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarBtnMouseExited
        // TODO add your handling code here:
        SetColores color = new SetColores(cancelarBtn);
    }//GEN-LAST:event_cancelarBtnMouseExited

    private void modificarBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarBtnMousePressed
        // TODO add your handling code here:
        MetodosBD2 metodos = new MetodosBD2();
        MetodosBD metodos2 = new MetodosBD();
        if(newContraTx.getText().length()>0 && confirmacionTxt.getText().length()>0){
            if(newContraTx.getText().equals(confirmacionTxt.getText())){
                 metodos.updateContraseUsuario(metodos2.getObtenerusuario(), newContraTx.getText());
                 newContraTx.setText("");
                 confirmacionTxt.setText("");
                 setVisible(false);
            }else{
                JOptionPane.showMessageDialog(null, "Confirmación no es correcta");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Debe de llenar todos los campos");
        }
    }//GEN-LAST:event_modificarBtnMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CambiarContra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CambiarContra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CambiarContra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CambiarContra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CambiarContra dialog = new CambiarContra(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cancelarBtn;
    private javax.swing.JPasswordField confirmacionTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel modificarBtn;
    private javax.swing.JPasswordField newContraTx;
    private javax.swing.JPanel panel1;
    // End of variables declaration//GEN-END:variables
}
