package perfil;

import Metodos.MetodosBD;
import Metodos.SetColores;
import Metodos.SetColores2;
import Metodos.SetColores3;
import java.awt.BorderLayout;

public class Perfil extends javax.swing.JPanel {

MetodosBD metodos=new MetodosBD(); 

    private int x=0;
    public Perfil() {
        initComponents();
        SetColores color1 = new SetColores(panel1);
        SetColores3 color2 = new SetColores3(panel2);
        SetColores color3 = new SetColores(modificarBtn);
        SetColores color4 = new SetColores(verFacturasBtn);
        SetColores3 color5 = new SetColores3(panel3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panel2 = new javax.swing.JPanel();
        modificarBtn = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        verFacturasBtn = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        panel3 = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setBackground(new java.awt.Color(204, 204, 204));
        panel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Source Code Pro", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Perfil");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(771, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 40));

        panel2.setBackground(new java.awt.Color(102, 102, 102));
        panel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        modificarBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        modificarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                modificarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                modificarBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                modificarBtnMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Información del perfil");

        javax.swing.GroupLayout modificarBtnLayout = new javax.swing.GroupLayout(modificarBtn);
        modificarBtn.setLayout(modificarBtnLayout);
        modificarBtnLayout.setHorizontalGroup(
            modificarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                .addContainerGap())
        );
        modificarBtnLayout.setVerticalGroup(
            modificarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modificarBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel2.add(modificarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 27, -1, -1));

        verFacturasBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        verFacturasBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verFacturasBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                verFacturasBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                verFacturasBtnMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Historial de compras");

        javax.swing.GroupLayout verFacturasBtnLayout = new javax.swing.GroupLayout(verFacturasBtn);
        verFacturasBtn.setLayout(verFacturasBtnLayout);
        verFacturasBtnLayout.setHorizontalGroup(
            verFacturasBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verFacturasBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                .addContainerGap())
        );
        verFacturasBtnLayout.setVerticalGroup(
            verFacturasBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verFacturasBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel2.add(verFacturasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 27, -1, 55));

        add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 880, 100));

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        add(panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 880, 470));
    }// </editor-fold>//GEN-END:initComponents

    private void modificarBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarBtnMousePressed
        // TODO add your handling code here:
        x=1;
        SetColores2 color = new SetColores2(modificarBtn);
        SetColores color1 = new SetColores(verFacturasBtn);
        
       if(metodos.getObtenertipo()==3){
            ModificarPerfil modificar=new ModificarPerfil();
        modificar.setSize(880,610);
        modificar.setLocation(0,0);
        panel3.removeAll();
        panel3.add(modificar,BorderLayout.CENTER);
        panel3.revalidate();
        panel3.repaint();
        }else{
            ModificarPerfil2 modificar2 = new ModificarPerfil2();
            modificar2.setSize(880, 470);
            modificar2.setLocation(0, 0);

            panel3.removeAll();
            panel3.add(modificar2, BorderLayout.CENTER);
            panel3.revalidate();
            panel3.repaint();
        }
        
    }//GEN-LAST:event_modificarBtnMousePressed

    private void verFacturasBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verFacturasBtnMousePressed
        // TODO add your handling code here:
        x=2;
        SetColores color = new SetColores(modificarBtn);
        SetColores2 color1 = new SetColores2(verFacturasBtn);
        
        HistorialCompras historial=new HistorialCompras();
        historial.setSize(880,470);
        historial.setLocation(0,0);
        
        panel3.removeAll();
        panel3.add(historial,BorderLayout.CENTER);
        panel3.revalidate();
        panel3.repaint();
        
    }//GEN-LAST:event_verFacturasBtnMousePressed

    private void modificarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarBtnMouseEntered
        // TODO add your handling code here:
        SetColores2 color2 = new SetColores2(modificarBtn);
    }//GEN-LAST:event_modificarBtnMouseEntered

    private void modificarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarBtnMouseExited
        // TODO add your handling code here:
        if(x==1){
            
        }else{
            SetColores color1 = new SetColores(modificarBtn);
        }
    }//GEN-LAST:event_modificarBtnMouseExited

    private void verFacturasBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verFacturasBtnMouseEntered
        // TODO add your handling code here:
        SetColores2 color1 = new SetColores2(verFacturasBtn);
    }//GEN-LAST:event_verFacturasBtnMouseEntered

    private void verFacturasBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verFacturasBtnMouseExited
        // TODO add your handling code here:
        if(x==2){
            
        }else{
            SetColores color1 = new SetColores(verFacturasBtn);
        }
    }//GEN-LAST:event_verFacturasBtnMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel modificarBtn;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JPanel verFacturasBtn;
    // End of variables declaration//GEN-END:variables
}
